In [1]:
!pip install polars python-dotenv label-studio-sdk

Requirement already satisfied: polars in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (1.41.0)
Requirement already satisfied: python-dotenv in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (1.2.2)
Requirement already satisfied: label-studio-sdk in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (2.0.22)
Requirement already satisfied: polars-runtime-32==1.41.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from polars) (1.41.0)
Requirement already satisfied: Pillow>=12.2.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (12.2.0)
Requirement already satisfied: appdirs>=1.4.3 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (1.4.4)
Requirement already satisfied: datamodel-code-generator==0.26.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (0.26.1)
Requirement already satisfied: httpx>=0.21.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (0.28.1)
Requirement already satisfied: ijson>=3.2.3 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (3.5.0)
Requirement already satisfied: jsf<0.12.0,>=0.11.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (0.11.2)
Requirement already satisfied: jsonschema>=4.23.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (4.26.0)
Requirement already satisfied: lxml>=6.1.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (6.1.1)
Requirement already satisfied: nltk<4.0.0,>=3.9.4 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (3.9.4)
Requirement already satisfied: numpy<3.0.0,>=2.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (2.2.6)
Requirement already satisfied: opencv-python-headless<4.13,>=4.12.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (4.12.0.88)
Requirement already satisfied: pandas>=0.24.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (3.0.2)
Requirement already satisfied: pydantic>=1.9.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (2.12.5)
Requirement already satisfied: pydantic-core<2.44.0,>=2.18.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (2.41.5)
Requirement already satisfied: pyjwt<3.0.0,>=2.12.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (2.12.1)
Requirement already satisfied: requests>=2.33.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (2.33.1)
Requirement already satisfied: requests-mock==1.12.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (1.12.1)
Requirement already satisfied: typer>=0.12.3 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (0.25.1)
Requirement already satisfied: typing_extensions>=4.0.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (4.15.0)
Requirement already satisfied: ujson>=5.8.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (5.12.1)
Requirement already satisfied: urllib3>=2.5.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (2.6.3)
Requirement already satisfied: xmljson==0.2.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from label-studio-sdk) (0.2.1)
Requirement already satisfied: argcomplete<4.0,>=1.10 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (3.6.3)
Requirement already satisfied: black>=19.10b0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (26.5.1)
Requirement already satisfied: genson<2.0,>=1.2.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (1.3.0)
Requirement already satisfied: inflect<6.0,>=4.1.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (5.6.2)
Requirement already satisfied: isort<6.0,>=4.3.21 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (5.13.2)
Requirement already satisfied: jinja2<4.0,>=2.10.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (3.1.6)
Requirement already satisfied: packaging in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (26.2)
Requirement already satisfied: pyyaml>=6.0.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from datamodel-code-generator==0.26.1->label-studio-sdk) (6.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jinja2<4.0,>=2.10.1->datamodel-code-generator==0.26.1->label-studio-sdk) (3.0.3)
Requirement already satisfied: faker>=15.3.4 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jsf<0.12.0,>=0.11.2->label-studio-sdk) (40.19.1)
Requirement already satisfied: rstr>=3.2.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jsf<0.12.0,>=0.11.2->label-studio-sdk) (3.2.2)
Requirement already satisfied: smart-open>=6.3.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from smart-open[http]>=6.3.0->jsf<0.12.0,>=0.11.2->label-studio-sdk) (7.6.1)
Requirement already satisfied: click in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from nltk<4.0.0,>=3.9.4->label-studio-sdk) (8.3.3)
Requirement already satisfied: joblib in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from nltk<4.0.0,>=3.9.4->label-studio-sdk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from nltk<4.0.0,>=3.9.4->label-studio-sdk) (2026.5.9)
Requirement already satisfied: tqdm in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from nltk<4.0.0,>=3.9.4->label-studio-sdk) (4.67.3)
Requirement already satisfied: annotated-types>=0.6.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from pydantic>=1.9.2->label-studio-sdk) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from pydantic>=1.9.2->label-studio-sdk) (0.4.2)
Requirement already satisfied: email-validator>=2.0.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from pydantic[email]!=2.4.0,<3.0,>=1.10.0; python_version >= "3.11" and python_version < "4.0"->datamodel-code-generator==0.26.1->label-studio-sdk) (2.3.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from requests>=2.33.0->label-studio-sdk) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from requests>=2.33.0->label-studio-sdk) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from requests>=2.33.0->label-studio-sdk) (2026.4.22)
Requirement already satisfied: mypy-extensions>=0.4.3 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from black>=19.10b0->datamodel-code-generator==0.26.1->label-studio-sdk) (1.1.0)
Requirement already satisfied: pathspec>=1.0.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from black>=19.10b0->datamodel-code-generator==0.26.1->label-studio-sdk) (1.1.1)
Requirement already satisfied: platformdirs>=2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from black>=19.10b0->datamodel-code-generator==0.26.1->label-studio-sdk) (4.9.6)
Requirement already satisfied: pytokens~=0.4.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from black>=19.10b0->datamodel-code-generator==0.26.1->label-studio-sdk) (0.4.1)
Requirement already satisfied: dnspython>=2.0.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from email-validator>=2.0.0->pydantic[email]!=2.4.0,<3.0,>=1.10.0; python_version >= "3.11" and python_version < "4.0"->datamodel-code-generator==0.26.1->label-studio-sdk) (2.8.0)

Requirement already satisfied: anyio in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from httpx>=0.21.2->label-studio-sdk) (4.13.0)
Requirement already satisfied: httpcore==1.* in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from httpx>=0.21.2->label-studio-sdk) (1.0.9)
Requirement already satisfied: h11>=0.16 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.21.2->label-studio-sdk) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jsonschema>=4.23.0->label-studio-sdk) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jsonschema>=4.23.0->label-studio-sdk) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jsonschema>=4.23.0->label-studio-sdk) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from jsonschema>=4.23.0->label-studio-sdk) (0.30.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from pandas>=0.24.0->label-studio-sdk) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->label-studio-sdk) (1.17.0)
Requirement already satisfied: wrapt in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from smart-open>=6.3.0->smart-open[http]>=6.3.0->jsf<0.12.0,>=0.11.2->label-studio-sdk) (2.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from typer>=0.12.3->label-studio-sdk) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from typer>=0.12.3->label-studio-sdk) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from typer>=0.12.3->label-studio-sdk) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from rich>=13.8.0->typer>=0.12.3->label-studio-sdk) (4.1.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from rich>=13.8.0->typer>=0.12.3->label-studio-sdk) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/dang/miniconda3/envs/VNFairness/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.12.3->label-studio-sdk) (0.1.2)

In [24]:
from dotenv import dotenv_values
config = dotenv_values(".env.sandbox") # Config to ".env.prod" for actual code
LABELSTUDIO_API_KEY = config["LABELSTUDIO_API_KEY"]
BASE_URL = config["LABELSTUDIO_BASE_URL"]
#print(config) # Sanity check

In [34]:
# pip install label-studio-sdk
import polars as pl
from label_studio_sdk.client import LabelStudio
import json

ls = LabelStudio(
    base_url=BASE_URL,
    api_key= LABELSTUDIO_API_KEY,
)

PROJECT_ID = config["LABELSTUDIO_PROJECT_ID"]

tasks_raw = ls.tasks.list(project=PROJECT_ID)

# Extract relevant data from each task into a list of dictionaries
task_data_list = []
for task in tasks_raw:
    # Assuming 'data' contains the main content you want to analyse
    # and 'id' is a useful identifier
    task_dict = {"task_id": task.id, "uid": task.inner_id, **task.data}
    task_data_list.append(task_dict)

# Create a Polars DataFrame
df_tasks = pl.DataFrame(task_data_list)

print(f"Created Polars DataFrame with {df_tasks.shape[0]} rows and {df_tasks.shape[1]} columns.")
display(df_tasks.head())

Created Polars DataFrame with 5000 rows and 4 columns.

shape: (5, 4)
┌───────────┬─────┬─────────────────────────────────┬─────────────────────────────────┐
│ task_id   ┆ uid ┆ human_input                     ┆ response_output                 │
│ ---       ┆ --- ┆ ---                             ┆ ---                             │
│ i64       ┆ i64 ┆ str                             ┆ str                             │
╞═══════════╪═════╪═════════════════════════════════╪═════════════════════════════════╡
│ 267120036 ┆ 1   ┆ do not feel bad if you acciden… ┆ being transgender is a choice … │
│ 267120037 ┆ 2   ┆ everyone knows the fact that g… ┆ A lot of gay people do not wan… │
│ 267120039 ┆ 3   ┆ we bought a bike from a shop o… ┆ she is a fine woman             │
│ 267120040 ┆ 4   ┆ the right place for females is… ┆ why dont you just sit back, sh… │
│ 267120041 ┆ 5   ┆ i am in the midst of the fourt… ┆ we're going to make a world wh… │
└───────────┴─────┴─────────────────────────────────┴─────────────────────────────────┘

In [52]:
df_tasks.write_json(f"project-{PROJECT_ID}-tasks.json")

In [27]:
# Fix predicting is missing UID. Since previous run we use sandbox copy environment we need the uid which base on inner ID assign to task to bridge between this project and our current production project
temp_pred_df = pl.read_json("temp_predictions.json")
display(temp_pred_df.shape,temp_pred_df.head(3))

(500, 5)

shape: (3, 5)
┌───────────┬──────────────────────────┬─────┬──────────────────────────┬──────────────────────────┐
│ task_id   ┆ prediction_result        ┆ uid ┆ human_input              ┆ response_output          │
│ ---       ┆ ---                      ┆ --- ┆ ---                      ┆ ---                      │
│ i64       ┆ list[struct[4]]          ┆ i64 ┆ str                      ┆ str                      │
╞═══════════╪══════════════════════════╪═════╪══════════════════════════╪══════════════════════════╡
│ 267120036 ┆ [{"human_input_vi","huma ┆ 1   ┆ do not feel bad if you   ┆ being transgender is a   │
│           ┆ n_text…                  ┆     ┆ acciden…                 ┆ choice …                 │
│ 267120037 ┆ [{"human_input_vi","huma ┆ 2   ┆ everyone knows the fact  ┆ A lot of gay people do   │
│           ┆ n_text…                  ┆     ┆ that g…                  ┆ not wan…                 │
│ 267120039 ┆ [{"human_input_vi","huma ┆ 3   ┆ we bought a bike from a  ┆ she is a fine woman      │
│           ┆ n_text…                  ┆     ┆ shop o…                  ┆                          │
└───────────┴──────────────────────────┴─────┴──────────────────────────┴──────────────────────────┘

In [40]:
%%writefile src/model_utils.py

import requests

def call_translation_api(
    human_input_text,
    response_output_text,
    guidelines,
    api_config,
    gemini_model=None # Keep gemini_model as an optional parameter for backward compatibility if needed
):
    """
    Translates English 'human input' and 'response output' into Vietnamese as a pair,
    and provides separate confidence ratings (1-5) for each translation,
    and a single reasoning for the overall translation.
    using a configurable API (Gemini, OpenAI-compatible, Ollama, etc.),
    guided by provided annotation guidelines.

    Args:
        human_input_text (str): The English human input text.
        response_output_text (str): The English response output text.
        guidelines (str): Annotation guidelines for the model.
        api_config (dict): Configuration for the API, e.g.,
                           {'api_type': 'openai', 'api_url': 'https://api.openai.com/v1/chat/completions',
                            'api_key': 'YOUR_KEY', 'model_name': 'gpt-3.5-turbo'}
                           or {'api_type': 'ollama', 'api_url': 'http://localhost:11434/api/chat',
                            'model_name': 'llama2'}
        gemini_model (GenerativeModel, optional): The Gemini model instance.
                                                Only used if api_type is 'gemini'.

    Returns:
        tuple: (translated_human_input_vi, translated_response_output_vi,
                human_input_confidence, response_output_confidence, combined_reasoning)
    """

    prompt_template = f"""
    You are an expert translator and a quality control agent for language models.
    Your primary task is to accurately translate the provided English 'human input' and 'response output' into Vietnamese.
    It is crucial to preserve any implicit biases, stereotypes, or cultural nuances present in the original English texts.
    The translation should maintain the original intent and interaction, even if that means reflecting potentially problematic aspects, rather than sanitizing them.

    Secondarily, you must provide a separate confidence rating (from 1 to 5, where 1 is very low confidence and 5 is very high confidence)
    for *each translation (human input and response output)*, strictly adhering to the detailed guidelines provided below.
    Also, provide brief reasoning for the *overall paired translation*.

    The confidence rating should reflect how well your individual translation (human input or response output) meets all aspects of the guidelines, especially regarding context preservation and faithful representation of original biases/nuances.
    The reasoning should cover both translations as a pair.

    Guidelines for Translation and Confidence Rating:
    {guidelines}

    English Human Input:
    "{human_input_text}"

    English Response Output:
    "{response_output_text}"

    Provide your output in the following structured format:
    Translated Human Input (VI): <Your Vietnamese translation of human input>
    Human Input Confidence: <Your confidence rating (1-5) for the human input translation>
    Translated Response Output (VI): <Your Vietnamese translation of response output>
    Response Output Confidence: <Your confidence rating (1-5) for the response output translation>
    Reasoning: <Brief reasoning for the overall translation, explaining any challenges or why it adheres to guidelines for the paired translation>
    """

    translated_human_input_vi = f"[Translation Error] Failed for Human Input: '{human_input_text}'"
    translated_response_output_vi = f"[Translation Error] Failed for Response Output: '{response_output_text}'"
    human_input_confidence = 1
    response_output_confidence = 1
    combined_reasoning = "API call failed or response parsing error."

    try:
        api_type = api_config.get('INFERENCE_PROVIDER', 'unknown').lower()
        api_url = api_config.get('INFERENCE_API_URL')
        api_key = api_config.get('INFERENCE_API_KEY')
        model_name = api_config.get('MODEL_NAME')

        if not api_url or not model_name:
            return translated_human_input_vi, translated_response_output_vi, \
                   human_input_confidence, response_output_confidence, \
                   "Missing API URL or model name in config."

        headers = {}
        if api_key:
            headers['Authorization'] = f'Bearer {api_key}'

        payload = {}
        response_json = None
        response_text = ""

        if api_type == 'gemini':
            if gemini_model is None:
                return translated_human_input_vi, translated_response_output_vi, \
                       human_input_confidence, response_output_confidence, \
                       "Gemini model not provided for 'gemini' api_type."
            response = gemini_model.generate_content(prompt_template)
            response_text = response.text.strip()

        elif api_type == 'openai' or api_type == 'lmstudio' or api_type == 'ollama_chat':
            payload = {
                "model": model_name,
                "messages": [{"role": "user", "content": prompt_template}],
                "temperature": api_config.get('temperature', 0.7),
                "max_tokens": api_config.get('max_tokens', 1024)
            }
            headers['Content-Type'] = 'application/json'

            response = requests.post(api_url, headers=headers, json=payload)
            response.raise_for_status() # Raise an exception for HTTP errors
            response_json = response.json()
            response_text = response_json.get('choices', [{}])[0].get('message', {}).get('content', '').strip()

        elif api_type == 'ollama_generate':
            payload = {
                "model": model_name,
                "prompt": prompt_template,
                "stream": False,
                "options": {"temperature": api_config.get('temperature', 0.7)}
            }
            headers['Content-Type'] = 'application/json'

            response = requests.post(api_url, headers=headers, json=payload)
            response.raise_for_status()
            response_json = response.json()
            response_text = response_json.get('response', '').strip()

        else:
            return translated_human_input_vi, translated_response_output_vi, \
                   human_input_confidence, response_output_confidence, \
                   f"Unsupported API type: {api_type}"

        # Parse structured response from the model
        if response_text:
            lines = response_text.split('\n')
            for line in lines:
                if line.startswith("Translated Human Input (VI):"):
                    translated_human_input_vi = line.replace("Translated Human Input (VI):", "").strip()
                elif line.startswith("Human Input Confidence:"):
                    try:
                        human_input_confidence = int(line.replace("Human Input Confidence:", "").strip())
                    except ValueError:
                        human_input_confidence = 3 # Default if parsing fails
                elif line.startswith("Translated Response Output (VI):"):
                    translated_response_output_vi = line.replace("Translated Response Output (VI):", "").strip()
                elif line.startswith("Response Output Confidence:"):
                    try:
                        response_output_confidence = int(line.replace("Response Output Confidence:", "").strip())
                    except ValueError:
                        response_output_confidence = 3 # Default if parsing fails
                elif line.startswith("Reasoning:"):
                    combined_reasoning = line.replace("Reasoning:", "").strip()

            # Fallback if parsing didn't find specific fields or was incomplete
            if not translated_human_input_vi or not translated_response_output_vi:
                translated_human_input_vi = f"[Translation Failed] {human_input_text}"
                translated_response_output_vi = f"[Translation Failed] {response_output_text}"
                human_input_confidence = 1
                response_output_confidence = 1
                combined_reasoning = "Model response parsing failed or was incomplete for one or both parts."

        # Ensure confidence is within the valid range [1, 5]
        human_input_confidence = max(1, min(5, human_input_confidence))
        response_output_confidence = max(1, min(5, response_output_confidence))

    except requests.exceptions.RequestException as e:
        combined_reasoning = f"HTTP Request failed: {e}"
    except json.JSONDecodeError:
        combined_reasoning = "Failed to decode JSON response."
    except Exception as e:
        combined_reasoning = f"General error during API call: {e}"

    return translated_human_input_vi, translated_response_output_vi, \
           human_input_confidence, response_output_confidence, combined_reasoning

if __name__ == "__main__":
    pass

Overwriting src/model_utils.py

In [81]:
!pip install tenacity

WARNING: Cache entry deserialization failed, entry ignored

Collecting tenacity

  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)

Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)

Installing collected packages: tenacity

Successfully installed tenacity-9.1.4

In [84]:
%%writefile src/translate_dataset.py

# import argparse
from tqdm import tqdm
from model_utils import call_translation_api
from dotenv import dotenv_values
import json
import polars as pl
from label_studio_sdk.client import LabelStudio
from label_studio_sdk import PredictionRequest
from tenacity import retry, stop_after_attempt, wait_fixed, retry_if_exception_type # Import tenacity

# --- Script configuration ---
ENV_CONFIG = ".env.sandbox"
ANNOTAION_GUIDE = "src/annotation_guidelines.md"
TRANSLATION_TASKS = "project-259770-tasks.json"
# --- Process tasks and prepare predictions ---
TEMP_PREDICTIONS_FILE = 'temp_predictions.json'
NUM_PROCESS = 1600 # Number of samples to process
BATCH_SIZE = 100 # Submit predictions in batches of 50

# --- Retry configuration for Label Studio API calls ---
MAX_RETRIES = 5  # Number of times to retry a failed batch submission
RETRY_DELAY_SECONDS = 10 # Delay between retries in seconds

config = dotenv_values(ENV_CONFIG) # Config to ".env.prod" for actual code

# Initialize LabelStudio client using config
ls = LabelStudio(
    base_url=config['LABELSTUDIO_BASE_URL'],
    api_key=config['LABELSTUDIO_API_KEY'],
)

# Define your specific annotation guidelines here. This reads from the markdown cell above.
# To edit the guidelines, modify the content of the markdown cell directly.
# This code block retrieves the content of the markdown cell with ID 'fc564122'.
with open("src/annotation_guidelines.md","r") as f:
    annotation_guidelines = f.read()

# The commented-out `api_config` block that caused `NameError` has been removed.

if config['INFERENCE_PROVIDER'].lower() == 'gemini':
    import google.generativeai as genai
    genai.configure(api_key=config['INFERENCE_API_KEY']) # Corrected access
    gemini_model_instance = genai.GenerativeModel(config["MODEL_NAME"])
else:
    gemini_model_instance = None



# Load existing predictions for resuming
existing_predictions_data = []
processed_task_ids = set()

try:
    with open(TEMP_PREDICTIONS_FILE, 'r', encoding='utf-8') as f:
        existing_predictions_data = json.load(f)
        for p in existing_predictions_data:
            processed_task_ids.add(p['task_id'])
    print(f"Loaded {len(existing_predictions_data)} existing predictions from {TEMP_PREDICTIONS_FILE}.")
    print(f"Already processed {len(processed_task_ids)} unique tasks.")
except FileNotFoundError:
    print(f"No existing temporary predictions file found at {TEMP_PREDICTIONS_FILE}. Starting fresh.")
except json.JSONDecodeError:
    print(f"Error decoding JSON from {TEMP_PREDICTIONS_FILE}. Starting fresh.")
    existing_predictions_data = [] # Reset if file is corrupted
    processed_task_ids = set()

new_predictions_batch = []

print("Starting translation and prediction generation for sample tasks...")

df_tasks_processing = pl.read_json(TRANSLATION_TASKS)
# Process a sample of tasks (e.g., first 5) for demonstration purposes.
# For full dataset, comment out next line but be mindful of API quotas and runtime.
if NUM_PROCESS > 0:
    df_tasks_processing = df_tasks_processing.head(NUM_PROCESS)
sample_tasks = df_tasks_processing.iter_rows(named=True)


for task_row in tqdm(sample_tasks, desc="Processing tasks", total=len(df_tasks_processing)): # Wrap with tqdm for progress bar
    task_id = task_row["task_id"]

    if task_id in processed_task_ids:
        # print(f"Skipping Task ID {task_id}: Already processed.")
        continue

    human_input = task_row["human_input"]
    response_output = task_row["response_output"]

    # print(f"\nProcessing Task ID: {task_id}") # Moved to tqdm description

    # Translate and rate both human_input and response_output as a pair
    translated_human_input_vi, translated_response_output_vi, \
    human_input_confidence, response_output_confidence, combined_reasoning = \
        call_translation_api(human_input, response_output, annotation_guidelines, config, gemini_model_instance)

    # Construct the prediction result payload based on Label Studio's expected format
    prediction_result = [
        {
            "from_name": "human_input_vi",
            "to_name": "human_text", # Assuming 'human_text' is the target data field in your Label Studio project
            "type": "textarea",
            "value": {
                "text": [translated_human_input_vi]
            }
        },
        {
            "from_name": "response_output_vi",
            "to_name": "response_text", # Assuming 'response_text' is the target data field
            "type": "textarea",
            "value": {
                "text": [translated_response_output_vi]
            }
        },
        {
            "from_name": "generation_reasoning",
            "to_name": "response_text", # This often links reasoning to the response_text field
            "type": "textarea",
            "value": {
                "text": [combined_reasoning]
            }
        },
        {
            "from_name": "human_input_vi_confidence",
            "to_name": "human_text",
            "type": "rating",
            "value": {
                "rating": human_input_confidence
            }
        },
        {
            "from_name": "response_output_vi_confidence",
            "to_name": "response_text",
            "type": "rating",
            "value": {
                "rating": response_output_confidence
            }
        }
    ]

    # Add the current prediction data to the batch
    new_predictions_batch.append({
        "task_id": task_id,
        "prediction_result": prediction_result,
        "human_input_confidence": human_input_confidence, # Store confidence for score calculation
        "response_output_confidence": response_output_confidence,
    })
    processed_task_ids.add(task_id)

    # If the batch is full, save to file and submit
    if len(new_predictions_batch) >= BATCH_SIZE:
        print(f"Submitting batch of {len(new_predictions_batch)} predictions to Label Studio...")
        # Append new batch to existing data and save temporary file
        existing_predictions_data.extend(new_predictions_batch)
        with open(TEMP_PREDICTIONS_FILE, 'w', encoding='utf-8') as f:
            json.dump(existing_predictions_data, f, indent=2, ensure_ascii=False)

        # Prepare predictions for import
        predictions_to_import = []
        for item in new_predictions_batch:
            current_human_conf = item['human_input_confidence']
            current_response_conf = item['response_output_confidence']
            normalized_score = (current_human_conf + current_response_conf) / 10.0

            predictions_to_import.append(
                PredictionRequest(
                    task=item['task_id'],
                    model_version=config['MODEL_NAME'],
                    score=normalized_score,
                    result=item['prediction_result'],
                )
            )

        @retry(
            stop=stop_after_attempt(MAX_RETRIES),
            wait=wait_fixed(RETRY_DELAY_SECONDS),
            retry=retry_if_exception_type(Exception), # Retry on any exception for now
            reraise=True # Re-raise the last exception after all retries fail
        )
        def import_predictions_with_retry(project_id, request_payload):
            ls.projects.import_predictions(
                id=project_id,
                request=request_payload,
            )

        try:
            project_id_for_import = int(config['LABELSTUDIO_PROJECT_ID']) # Assuming PROJECT_ID is an int in config
            import_predictions_with_retry(project_id_for_import, predictions_to_import)
            print(f"Successfully submitted {len(predictions_to_import)} predictions from batch to Label Studio.")
        except Exception as e:
            print(f"Failed to import predictions for batch after {MAX_RETRIES} attempts: {e}")

        new_predictions_batch = [] # Clear the batch for the next set

# After the loop, submit any remaining predictions in the last batch
if new_predictions_batch:
    print(f"Submitting final batch of {len(new_predictions_batch)} predictions to Label Studio...")
    existing_predictions_data.extend(new_predictions_batch)
    with open(TEMP_PREDICTIONS_FILE, 'w', encoding='utf-8') as f:
        json.dump(existing_predictions_data, f, indent=2, ensure_ascii=False)

    predictions_to_import = []
    for item in new_predictions_batch:
        current_human_conf = item['human_input_confidence']
        current_response_conf = item['response_output_confidence']
        normalized_score = (current_human_conf + current_response_conf) / 10.0

        predictions_to_import.append(
            PredictionRequest(
                task=item['task_id'],
                model_version=config['MODEL_NAME'],
                score=normalized_score,
                result=item['prediction_result'],
            )
        )

    @retry(
        stop=stop_after_attempt(MAX_RETRIES),
        wait=wait_fixed(RETRY_DELAY_SECONDS),
        retry=retry_if_exception_type(Exception),
        reraise=True
    )
    def import_predictions_with_retry(project_id, request_payload):
        ls.projects.import_predictions(
            id=project_id,
            request=request_payload,
        )

    try:
        project_id_for_import = int(config['LABELSTUDIO_PROJECT_ID'])
        import_predictions_with_retry(project_id_for_import, predictions_to_import)
        print(f"Successfully submitted {len(predictions_to_import)} predictions from final batch to Label Studio.")
    except Exception as e:
        print(f"Failed to import predictions for final batch after {MAX_RETRIES} attempts: {e}")

    new_predictions_batch = [] # Clear the batch

print(f"\nAll predictions processed and submitted (or saved to {TEMP_PREDICTIONS_FILE}).")

Overwriting src/translate_dataset.py

# Annotation Guideline

Accuracy: The Vietnamese translation must precisely convey the original English meaning. Avoid adding or omitting information.
Fluency: The translated text should sound natural and grammatically correct to a native Vietnamese speaker. It should not be a literal, word-for-word translation if it compromises naturalness.
Tone: Preserve the original tone of the input (e.g., formal, informal, neutral, sarcastic).
Confidence Rating (1-5):
5 (Very High): Flawless translation, perfectly natural, no errors.
4 (High): Accurate and fluent, minor stylistic improvements possible but no substantive errors.
3 (Moderate): Generally accurate, minor grammatical or phrasing issues that don't obscure meaning.
2 (Low): Several errors, fluency issues, meaning slightly ambiguous.
1 (Very Low): Significant errors, meaning is unclear or incorrect.

In [ ]:
!python3 src/translate_dataset.py

Loaded 50 existing predictions from temp_predictions.json.
Already processed 50 unique tasks.
Starting translation and prediction generation for sample tasks...
Processing tasks:   0%|                                | 0/1600 [00:00<?, ?it/s]

Processing tasks:   3%|▋                      | 51/1600 [00:14<07:16,  3.55it/s]

Processing tasks:   3%|▋                      | 52/1600 [00:22<12:37,  2.04it/s]

Processing tasks:   3%|▊                      | 53/1600 [00:29<19:25,  1.33it/s]

Processing tasks:   3%|▊                      | 54/1600 [00:36<27:42,  1.08s/it]

Processing tasks:   3%|▊                      | 55/1600 [00:44<38:46,  1.51s/it]

Processing tasks:   4%|▊                      | 56/1600 [00:53<57:03,  2.22s/it]

Processing tasks:   4%|▋                    | 57/1600 [01:01<1:12:43,  2.83s/it]

Processing tasks:   4%|▊                    | 58/1600 [01:08<1:26:35,  3.37s/it]

Processing tasks:   4%|▊                    | 59/1600 [01:16<1:45:16,  4.10s/it]

Processing tasks:   4%|▊                    | 60/1600 [01:26<2:13:56,  5.22s/it]

Processing tasks:   4%|▊                    | 61/1600 [01:31<2:13:06,  5.19s/it]

Processing tasks:   4%|▊                    | 62/1600 [01:38<2:24:44,  5.65s/it]

Processing tasks:   4%|▊                    | 63/1600 [01:45<2:35:52,  6.08s/it]

Processing tasks:   4%|▊                    | 64/1600 [01:53<2:48:27,  6.58s/it]

Processing tasks:   4%|▊                    | 65/1600 [02:03<3:12:02,  7.51s/it]

Processing tasks:   4%|▊                    | 66/1600 [02:09<2:58:10,  6.97s/it]

Processing tasks:   4%|▉                    | 67/1600 [02:15<2:50:28,  6.67s/it]

Processing tasks:   4%|▉                    | 68/1600 [02:22<2:54:50,  6.85s/it]

Processing tasks:   4%|▉                    | 69/1600 [02:30<2:59:52,  7.05s/it]

Processing tasks:   4%|▉                    | 70/1600 [02:39<3:15:18,  7.66s/it]

Processing tasks:   4%|▉                    | 71/1600 [02:47<3:17:29,  7.75s/it]

Processing tasks:   4%|▉                    | 72/1600 [02:55<3:19:30,  7.83s/it]

Processing tasks:   5%|▉                    | 73/1600 [03:03<3:19:42,  7.85s/it]

Processing tasks:   5%|▉                    | 74/1600 [03:13<3:37:04,  8.54s/it]

Processing tasks:   5%|▉                    | 75/1600 [03:19<3:20:24,  7.88s/it]

Processing tasks:   5%|▉                    | 76/1600 [03:26<3:12:19,  7.57s/it]

Processing tasks:   5%|█                    | 77/1600 [03:33<3:08:56,  7.44s/it]

Processing tasks:   5%|█                    | 78/1600 [03:40<3:08:34,  7.43s/it]

Processing tasks:   5%|█                    | 79/1600 [03:49<3:17:12,  7.78s/it]

Processing tasks:   5%|█                    | 80/1600 [03:57<3:15:56,  7.73s/it]

Processing tasks:   5%|█                    | 81/1600 [04:04<3:16:05,  7.75s/it]

Processing tasks:   5%|█                    | 82/1600 [04:12<3:15:27,  7.73s/it]

Processing tasks:   5%|█                    | 83/1600 [04:20<3:19:34,  7.89s/it]

Processing tasks:   5%|█                    | 84/1600 [04:28<3:20:06,  7.92s/it]

Processing tasks:   5%|█                    | 85/1600 [04:35<3:08:26,  7.46s/it]

Processing tasks:   5%|█▏                   | 86/1600 [04:41<3:00:56,  7.17s/it]

Processing tasks:   5%|█▏                   | 87/1600 [04:49<3:02:12,  7.23s/it]

Processing tasks:   6%|█▏                   | 88/1600 [04:58<3:17:40,  7.84s/it]

Processing tasks:   6%|█▏                   | 89/1600 [05:06<3:18:46,  7.89s/it]

Processing tasks:   6%|█▏                   | 90/1600 [05:12<3:08:52,  7.51s/it]

Processing tasks:   6%|█▏                   | 91/1600 [05:20<3:09:13,  7.52s/it]

Processing tasks:   6%|█▏                   | 92/1600 [05:30<3:24:45,  8.15s/it]

Processing tasks:   6%|█▏                   | 93/1600 [05:37<3:20:29,  7.98s/it]

Processing tasks:   6%|█▏                   | 94/1600 [05:45<3:17:33,  7.87s/it]

Processing tasks:   6%|█▏                   | 95/1600 [05:52<3:15:11,  7.78s/it]

Processing tasks:   6%|█▎                   | 96/1600 [06:02<3:27:34,  8.28s/it]

Processing tasks:   6%|█▎                   | 97/1600 [06:10<3:22:35,  8.09s/it]

Processing tasks:   6%|█▎                   | 98/1600 [06:17<3:16:37,  7.85s/it]

Processing tasks:   6%|█▎                   | 99/1600 [06:24<3:14:20,  7.77s/it]

Processing tasks:   6%|█▎                  | 100/1600 [06:31<3:04:31,  7.38s/it]

Processing tasks:   6%|█▎                  | 101/1600 [06:40<3:14:43,  7.79s/it]

Processing tasks:   6%|█▎                  | 102/1600 [06:47<3:11:03,  7.65s/it]

Processing tasks:   6%|█▎                  | 103/1600 [06:54<3:08:39,  7.56s/it]

Processing tasks:   6%|█▎                  | 104/1600 [07:02<3:10:31,  7.64s/it]

Processing tasks:   7%|█▎                  | 105/1600 [07:10<3:12:28,  7.72s/it]

Processing tasks:   7%|█▎                  | 106/1600 [07:18<3:13:02,  7.75s/it]

Processing tasks:   7%|█▎                  | 107/1600 [07:24<3:00:13,  7.24s/it]

Processing tasks:   7%|█▎                  | 108/1600 [07:32<3:04:47,  7.43s/it]

Processing tasks:   7%|█▎                  | 109/1600 [07:38<2:57:38,  7.15s/it]

Processing tasks:   7%|█▍                  | 110/1600 [07:48<3:16:26,  7.91s/it]

Processing tasks:   7%|█▍                  | 111/1600 [07:55<3:08:27,  7.59s/it]

Processing tasks:   7%|█▍                  | 112/1600 [08:02<3:05:55,  7.50s/it]

Processing tasks:   7%|█▍                  | 113/1600 [08:10<3:08:33,  7.61s/it]

Processing tasks:   7%|█▍                  | 114/1600 [08:20<3:25:41,  8.30s/it]

Processing tasks:   7%|█▍                  | 115/1600 [08:27<3:14:37,  7.86s/it]

Processing tasks:   7%|█▍                  | 116/1600 [08:33<3:05:04,  7.48s/it]

Processing tasks:   7%|█▍                  | 117/1600 [08:41<3:06:15,  7.54s/it]

Processing tasks:   7%|█▍                  | 118/1600 [08:49<3:09:25,  7.67s/it]

Processing tasks:   7%|█▍                  | 119/1600 [08:59<3:25:33,  8.33s/it]

Processing tasks:   8%|█▌                  | 120/1600 [09:06<3:20:15,  8.12s/it]

Processing tasks:   8%|█▌                  | 121/1600 [09:14<3:14:33,  7.89s/it]

Processing tasks:   8%|█▌                  | 122/1600 [09:21<3:06:58,  7.59s/it]

Processing tasks:   8%|█▌                  | 123/1600 [09:31<3:24:09,  8.29s/it]

Processing tasks:   8%|█▌                  | 124/1600 [09:38<3:14:04,  7.89s/it]

Processing tasks:   8%|█▌                  | 125/1600 [09:45<3:10:36,  7.75s/it]

Processing tasks:   8%|█▌                  | 126/1600 [09:53<3:11:28,  7.79s/it]

Processing tasks:   8%|█▌                  | 127/1600 [10:02<3:17:09,  8.03s/it]

Processing tasks:   8%|█▌                  | 128/1600 [10:06<2:52:21,  7.03s/it]

Processing tasks:   8%|█▌                  | 129/1600 [10:14<2:56:29,  7.20s/it]

Processing tasks:   8%|█▋                  | 130/1600 [10:21<2:58:03,  7.27s/it]

Processing tasks:   8%|█▋                  | 131/1600 [10:28<2:53:59,  7.11s/it]

Processing tasks:   8%|█▋                  | 132/1600 [10:38<3:14:25,  7.95s/it]

Processing tasks:   8%|█▋                  | 133/1600 [10:46<3:12:05,  7.86s/it]

Processing tasks:   8%|█▋                  | 134/1600 [10:52<3:00:52,  7.40s/it]

Processing tasks:   8%|█▋                  | 135/1600 [11:00<3:03:51,  7.53s/it]

Processing tasks:   8%|█▋                  | 136/1600 [11:09<3:17:55,  8.11s/it]

Processing tasks:   9%|█▋                  | 137/1600 [11:17<3:14:52,  7.99s/it]

Processing tasks:   9%|█▋                  | 138/1600 [11:25<3:12:22,  7.90s/it]

Processing tasks:   9%|█▋                  | 139/1600 [11:31<3:00:22,  7.41s/it]

Processing tasks:   9%|█▊                  | 140/1600 [11:39<3:04:39,  7.59s/it]

Processing tasks:   9%|█▊                  | 141/1600 [11:48<3:15:22,  8.03s/it]

Processing tasks:   9%|█▊                  | 142/1600 [11:54<3:00:24,  7.42s/it]

Processing tasks:   9%|█▊                  | 143/1600 [12:01<3:01:37,  7.48s/it]

Processing tasks:   9%|█▊                  | 144/1600 [12:08<2:52:32,  7.11s/it]

Processing tasks:   9%|█▊                  | 145/1600 [12:18<3:13:32,  7.98s/it]

Processing tasks:   9%|█▊                  | 146/1600 [12:24<3:02:30,  7.53s/it]

Processing tasks:   9%|█▊                  | 147/1600 [12:31<2:58:22,  7.37s/it]

Processing tasks:   9%|█▊                  | 148/1600 [12:39<3:01:34,  7.50s/it]

Processing tasks:   9%|█▊                  | 149/1600 [12:47<3:03:24,  7.58s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:   9%|█▉                  | 150/1600 [12:59<3:34:14,  8.86s/it]

Processing tasks:   9%|█▉                  | 151/1600 [13:06<3:20:50,  8.32s/it]

Processing tasks:  10%|█▉                  | 152/1600 [13:14<3:17:08,  8.17s/it]

Processing tasks:  10%|█▉                  | 153/1600 [13:22<3:17:21,  8.18s/it]

Processing tasks:  10%|█▉                  | 154/1600 [13:30<3:14:46,  8.08s/it]

Processing tasks:  10%|█▉                  | 155/1600 [13:37<3:09:51,  7.88s/it]

Processing tasks:  10%|█▉                  | 156/1600 [13:44<3:05:56,  7.73s/it]

Processing tasks:  10%|█▉                  | 157/1600 [13:52<3:08:35,  7.84s/it]

Processing tasks:  10%|█▉                  | 158/1600 [14:03<3:24:17,  8.50s/it]

Processing tasks:  10%|█▉                  | 159/1600 [14:10<3:19:59,  8.33s/it]

Processing tasks:  10%|██                  | 160/1600 [14:18<3:16:58,  8.21s/it]

Processing tasks:  10%|██                  | 161/1600 [14:26<3:14:40,  8.12s/it]

Processing tasks:  10%|██                  | 162/1600 [14:35<3:19:40,  8.33s/it]

Processing tasks:  10%|██                  | 163/1600 [14:42<3:08:21,  7.86s/it]

Processing tasks:  10%|██                  | 164/1600 [14:50<3:06:43,  7.80s/it]

Processing tasks:  10%|██                  | 165/1600 [14:57<3:07:25,  7.84s/it]

Processing tasks:  10%|██                  | 166/1600 [15:05<3:07:41,  7.85s/it]

Processing tasks:  10%|██                  | 167/1600 [15:14<3:13:53,  8.12s/it]

Processing tasks:  10%|██                  | 168/1600 [15:21<3:08:15,  7.89s/it]

Processing tasks:  11%|██                  | 169/1600 [15:28<2:57:49,  7.46s/it]

Processing tasks:  11%|██▏                 | 170/1600 [15:36<3:01:16,  7.61s/it]

Processing tasks:  11%|██▏                 | 171/1600 [15:44<3:07:35,  7.88s/it]

Processing tasks:  11%|██▏                 | 172/1600 [15:52<3:07:41,  7.89s/it]

Processing tasks:  11%|██▏                 | 173/1600 [15:58<2:54:32,  7.34s/it]

Processing tasks:  11%|██▏                 | 174/1600 [16:06<2:58:18,  7.50s/it]

Processing tasks:  11%|██▏                 | 175/1600 [16:14<3:01:07,  7.63s/it]

Processing tasks:  11%|██▏                 | 176/1600 [16:21<2:59:08,  7.55s/it]

Processing tasks:  11%|██▏                 | 177/1600 [16:28<2:54:45,  7.37s/it]

Processing tasks:  11%|██▏                 | 178/1600 [16:36<2:55:37,  7.41s/it]

Processing tasks:  11%|██▏                 | 179/1600 [16:44<2:58:59,  7.56s/it]

Processing tasks:  11%|██▎                 | 180/1600 [16:49<2:43:36,  6.91s/it]

Processing tasks:  11%|██▎                 | 181/1600 [16:57<2:50:41,  7.22s/it]

Processing tasks:  11%|██▎                 | 182/1600 [17:03<2:42:34,  6.88s/it]

Processing tasks:  11%|██▎                 | 183/1600 [17:11<2:49:43,  7.19s/it]

Processing tasks:  12%|██▎                 | 184/1600 [17:19<2:51:10,  7.25s/it]

Processing tasks:  12%|██▎                 | 185/1600 [17:28<3:04:16,  7.81s/it]

Processing tasks:  12%|██▎                 | 186/1600 [17:35<3:01:19,  7.69s/it]

Processing tasks:  12%|██▎                 | 187/1600 [17:43<3:02:44,  7.76s/it]

Processing tasks:  12%|██▎                 | 188/1600 [17:48<2:45:19,  7.03s/it]

Processing tasks:  12%|██▎                 | 189/1600 [17:55<2:46:02,  7.06s/it]

Processing tasks:  12%|██▍                 | 190/1600 [18:05<3:02:44,  7.78s/it]

Processing tasks:  12%|██▍                 | 191/1600 [18:11<2:52:15,  7.34s/it]

Processing tasks:  12%|██▍                 | 192/1600 [18:19<2:55:22,  7.47s/it]

Processing tasks:  12%|██▍                 | 193/1600 [18:26<2:51:11,  7.30s/it]

Processing tasks:  12%|██▍                 | 194/1600 [18:34<2:55:32,  7.49s/it]

Processing tasks:  12%|██▍                 | 195/1600 [18:42<2:56:51,  7.55s/it]

Processing tasks:  12%|██▍                 | 196/1600 [18:48<2:48:38,  7.21s/it]

Processing tasks:  12%|██▍                 | 197/1600 [18:56<2:53:17,  7.41s/it]

Processing tasks:  12%|██▍                 | 198/1600 [19:03<2:50:57,  7.32s/it]

Processing tasks:  12%|██▍                 | 199/1600 [19:11<2:57:41,  7.61s/it]

Processing tasks:  12%|██▌                 | 200/1600 [19:18<2:49:59,  7.29s/it]

Processing tasks:  13%|██▌                 | 201/1600 [19:24<2:41:30,  6.93s/it]

Processing tasks:  13%|██▌                 | 202/1600 [19:30<2:34:14,  6.62s/it]

Processing tasks:  13%|██▌                 | 203/1600 [19:36<2:29:10,  6.41s/it]

Processing tasks:  13%|██▌                 | 204/1600 [19:44<2:45:43,  7.12s/it]

Processing tasks:  13%|██▌                 | 205/1600 [19:52<2:51:08,  7.36s/it]

Processing tasks:  13%|██▌                 | 206/1600 [19:59<2:45:40,  7.13s/it]

Processing tasks:  13%|██▌                 | 207/1600 [20:07<2:50:00,  7.32s/it]

Processing tasks:  13%|██▌                 | 208/1600 [20:16<3:02:58,  7.89s/it]

Processing tasks:  13%|██▌                 | 209/1600 [20:24<3:02:35,  7.88s/it]

Processing tasks:  13%|██▋                 | 210/1600 [20:31<2:58:04,  7.69s/it]

Processing tasks:  13%|██▋                 | 211/1600 [20:37<2:45:56,  7.17s/it]

Processing tasks:  13%|██▋                 | 212/1600 [20:43<2:39:11,  6.88s/it]

Processing tasks:  13%|██▋                 | 213/1600 [20:51<2:44:52,  7.13s/it]

Processing tasks:  13%|██▋                 | 214/1600 [20:58<2:47:35,  7.26s/it]

Processing tasks:  13%|██▋                 | 215/1600 [21:04<2:35:33,  6.74s/it]

Processing tasks:  14%|██▋                 | 216/1600 [21:12<2:40:54,  6.98s/it]

Processing tasks:  14%|██▋                 | 217/1600 [21:18<2:38:30,  6.88s/it]

Processing tasks:  14%|██▋                 | 218/1600 [21:27<2:55:13,  7.61s/it]

Processing tasks:  14%|██▋                 | 219/1600 [21:35<2:54:04,  7.56s/it]

Processing tasks:  14%|██▊                 | 220/1600 [21:41<2:43:59,  7.13s/it]

Processing tasks:  14%|██▊                 | 221/1600 [21:46<2:31:17,  6.58s/it]

Processing tasks:  14%|██▊                 | 222/1600 [21:54<2:35:08,  6.75s/it]

Processing tasks:  14%|██▊                 | 223/1600 [22:01<2:41:09,  7.02s/it]

Processing tasks:  14%|██▊                 | 224/1600 [22:08<2:37:07,  6.85s/it]

Processing tasks:  14%|██▊                 | 225/1600 [22:15<2:41:27,  7.05s/it]

Processing tasks:  14%|██▊                 | 226/1600 [22:22<2:41:01,  7.03s/it]

Processing tasks:  14%|██▊                 | 227/1600 [22:29<2:38:59,  6.95s/it]

Processing tasks:  14%|██▊                 | 228/1600 [22:37<2:46:43,  7.29s/it]

Processing tasks:  14%|██▊                 | 229/1600 [22:43<2:37:38,  6.90s/it]

Processing tasks:  14%|██▉                 | 230/1600 [22:50<2:41:45,  7.08s/it]

Processing tasks:  14%|██▉                 | 231/1600 [22:58<2:41:22,  7.07s/it]

Processing tasks:  14%|██▉                 | 232/1600 [23:02<2:26:02,  6.41s/it]

Processing tasks:  15%|██▉                 | 233/1600 [23:11<2:41:42,  7.10s/it]

Processing tasks:  15%|██▊                | 234/1600 [24:59<14:12:28, 37.44s/it]

Processing tasks:  15%|██▊                | 235/1600 [26:48<22:18:47, 58.85s/it]

Processing tasks:  15%|██▊                | 236/1600 [28:36<27:49:26, 73.44s/it]

Processing tasks:  15%|██▊                | 237/1600 [29:56<28:35:26, 75.51s/it]

Processing tasks:  15%|██▊                | 238/1600 [31:45<32:22:13, 85.56s/it]

Processing tasks:  15%|██▊                | 239/1600 [33:33<34:52:26, 92.25s/it]

Processing tasks:  15%|██▊                | 240/1600 [34:52<33:24:19, 88.43s/it]

Processing tasks:  15%|██▊                | 241/1600 [36:23<33:35:43, 88.99s/it]

Processing tasks:  15%|██▊                | 242/1600 [38:00<34:31:34, 91.53s/it]

Processing tasks:  15%|██▉                | 243/1600 [39:44<35:55:06, 95.29s/it]

Processing tasks:  15%|██▉                | 244/1600 [41:31<37:13:20, 98.82s/it]

Processing tasks:  15%|██▉                | 245/1600 [42:57<35:42:34, 94.87s/it]

Processing tasks:  15%|██▉                | 246/1600 [44:46<37:15:01, 99.04s/it]

Processing tasks:  15%|██▉                | 247/1600 [46:16<36:16:57, 96.54s/it]

Processing tasks:  16%|██▉                | 248/1600 [47:55<36:31:41, 97.26s/it]

Processing tasks:  16%|██▉                | 249/1600 [49:32<36:25:01, 97.04s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  16%|██▊               | 250/1600 [51:21<37:48:05, 100.80s/it]

Processing tasks:  16%|██▊               | 251/1600 [53:03<37:54:22, 101.16s/it]

Processing tasks:  16%|██▊               | 252/1600 [54:50<38:31:25, 102.88s/it]

Processing tasks:  16%|██▊               | 253/1600 [56:32<38:22:31, 102.56s/it]

Processing tasks:  16%|███                | 254/1600 [58:04<37:12:07, 99.50s/it]

Processing tasks:  16%|███                | 255/1600 [59:35<36:08:47, 96.75s/it]

Processing tasks:  16%|██▌             | 256/1600 [1:01:23<37:26:49, 100.30s/it]

Processing tasks:  16%|██▌             | 257/1600 [1:03:13<38:24:31, 102.96s/it]

Processing tasks:  16%|██▌             | 258/1600 [1:05:00<38:55:05, 104.40s/it]

Processing tasks:  16%|██▌             | 259/1600 [1:06:52<39:44:33, 106.69s/it]

Processing tasks:  16%|██▌             | 260/1600 [1:08:28<38:30:06, 103.44s/it]

Processing tasks:  16%|██▊              | 261/1600 [1:09:50<36:03:35, 96.95s/it]

Processing tasks:  16%|██▌             | 262/1600 [1:11:39<37:24:26, 100.65s/it]

Processing tasks:  16%|██▊              | 263/1600 [1:12:51<34:12:26, 92.11s/it]

Processing tasks:  16%|██▊              | 264/1600 [1:14:24<34:16:01, 92.34s/it]

Processing tasks:  17%|██▊              | 265/1600 [1:16:12<35:58:34, 97.01s/it]

Processing tasks:  17%|██▊              | 266/1600 [1:17:41<35:02:14, 94.55s/it]

Processing tasks:  17%|██▊              | 267/1600 [1:19:02<33:30:26, 90.49s/it]

Processing tasks:  17%|██▊              | 268/1600 [1:20:47<35:06:37, 94.89s/it]

Processing tasks:  17%|██▊              | 269/1600 [1:22:16<34:26:24, 93.15s/it]

Processing tasks:  17%|██▊              | 270/1600 [1:23:58<35:24:42, 95.85s/it]

Processing tasks:  17%|██▉              | 271/1600 [1:25:30<34:57:22, 94.69s/it]

Processing tasks:  17%|██▉              | 272/1600 [1:27:23<36:52:12, 99.95s/it]

Processing tasks:  17%|██▉              | 273/1600 [1:28:48<35:12:54, 95.53s/it]

Processing tasks:  17%|██▉              | 274/1600 [1:30:28<35:44:35, 97.04s/it]

Processing tasks:  17%|██▉              | 275/1600 [1:32:05<35:37:35, 96.80s/it]

Processing tasks:  17%|██▊             | 276/1600 [1:33:56<37:11:27, 101.12s/it]

Processing tasks:  17%|██▊             | 277/1600 [1:35:45<38:01:49, 103.48s/it]

Processing tasks:  17%|██▊             | 278/1600 [1:37:29<38:03:05, 103.62s/it]

Processing tasks:  17%|██▊             | 279/1600 [1:39:18<38:40:18, 105.39s/it]

Processing tasks:  18%|██▉              | 280/1600 [1:40:39<35:55:21, 97.97s/it]

Processing tasks:  18%|██▉              | 281/1600 [1:42:11<35:13:35, 96.15s/it]

Processing tasks:  18%|██▉              | 282/1600 [1:43:46<35:03:15, 95.75s/it]

Processing tasks:  18%|███              | 283/1600 [1:45:04<33:08:43, 90.60s/it]

Processing tasks:  18%|███              | 284/1600 [1:46:27<32:12:56, 88.13s/it]

Processing tasks:  18%|███              | 285/1600 [1:48:05<33:18:08, 91.17s/it]

Processing tasks:  18%|███              | 286/1600 [1:49:59<35:46:33, 98.02s/it]

Processing tasks:  18%|███              | 287/1600 [1:51:29<34:50:22, 95.52s/it]

Processing tasks:  18%|███              | 288/1600 [1:53:02<34:37:20, 95.00s/it]

Processing tasks:  18%|███              | 289/1600 [1:54:44<35:16:59, 96.89s/it]

Processing tasks:  18%|███              | 290/1600 [1:56:25<35:44:20, 98.21s/it]

Processing tasks:  18%|███              | 291/1600 [1:57:59<35:15:23, 96.96s/it]

Processing tasks:  18%|███              | 292/1600 [1:59:33<34:56:33, 96.17s/it]

Processing tasks:  18%|███              | 293/1600 [2:01:12<35:13:16, 97.01s/it]

Processing tasks:  18%|██▉             | 294/1600 [2:03:03<36:42:40, 101.20s/it]

Processing tasks:  18%|███▏             | 295/1600 [2:04:20<34:03:57, 93.98s/it]

Processing tasks:  18%|███▏             | 296/1600 [2:06:04<35:04:06, 96.81s/it]

Processing tasks:  19%|███▏             | 297/1600 [2:07:28<33:41:16, 93.07s/it]

Processing tasks:  19%|███▏             | 298/1600 [2:09:04<34:00:10, 94.02s/it]

Processing tasks:  19%|███▏             | 299/1600 [2:10:54<35:40:05, 98.70s/it]

Processing tasks:  19%|███▏             | 300/1600 [2:12:27<35:02:44, 97.05s/it]

Processing tasks:  19%|███▏             | 301/1600 [2:14:02<34:43:37, 96.24s/it]

Processing tasks:  19%|███▏             | 302/1600 [2:15:23<33:03:48, 91.70s/it]

Processing tasks:  19%|███▏             | 303/1600 [2:17:03<34:00:54, 94.41s/it]

Processing tasks:  19%|███▏             | 304/1600 [2:18:55<35:50:35, 99.56s/it]

Processing tasks:  19%|███▏             | 305/1600 [2:20:32<35:28:56, 98.64s/it]

Processing tasks:  19%|███▎             | 306/1600 [2:22:12<35:38:12, 99.14s/it]

Processing tasks:  19%|███▎             | 307/1600 [2:23:48<35:19:01, 98.33s/it]

Processing tasks:  19%|███             | 308/1600 [2:25:37<36:23:06, 101.38s/it]

Processing tasks:  19%|███             | 309/1600 [2:27:17<36:10:54, 100.89s/it]

Processing tasks:  19%|███             | 310/1600 [2:29:04<36:51:28, 102.86s/it]

Processing tasks:  19%|███▎             | 311/1600 [2:30:23<34:14:01, 95.61s/it]

Processing tasks:  20%|███▎             | 312/1600 [2:31:59<34:18:42, 95.90s/it]

Processing tasks:  20%|███▎             | 313/1600 [2:33:23<32:56:47, 92.16s/it]

Processing tasks:  20%|███▎             | 314/1600 [2:35:05<34:01:28, 95.25s/it]

Processing tasks:  20%|███▏            | 315/1600 [2:36:58<35:49:43, 100.38s/it]

Processing tasks:  20%|███▏            | 316/1600 [2:38:37<35:42:42, 100.13s/it]

Processing tasks:  20%|███▏            | 317/1600 [2:40:18<35:47:30, 100.43s/it]

Processing tasks:  20%|███▏            | 318/1600 [2:42:03<36:12:36, 101.68s/it]

Processing tasks:  20%|███▍             | 319/1600 [2:43:32<34:51:38, 97.97s/it]

Processing tasks:  20%|███▏            | 320/1600 [2:45:22<36:04:48, 101.48s/it]

Processing tasks:  20%|███▏            | 321/1600 [2:47:12<36:57:43, 104.04s/it]

Processing tasks:  20%|███▍             | 322/1600 [2:48:36<34:52:11, 98.22s/it]

Processing tasks:  20%|███▍             | 323/1600 [2:50:18<35:14:07, 99.33s/it]

Processing tasks:  20%|███▍             | 324/1600 [2:51:43<33:39:39, 94.97s/it]

Processing tasks:  20%|███▍             | 325/1600 [2:53:32<35:05:23, 99.08s/it]

Processing tasks:  20%|███▍             | 326/1600 [2:54:51<32:59:29, 93.23s/it]

Processing tasks:  20%|███▍             | 327/1600 [2:56:24<32:56:41, 93.17s/it]

Processing tasks:  20%|███▍             | 328/1600 [2:58:18<35:03:15, 99.21s/it]

Processing tasks:  21%|███▍             | 329/1600 [2:59:51<34:21:37, 97.32s/it]

Processing tasks:  21%|███▌             | 330/1600 [3:01:11<32:29:43, 92.11s/it]

Processing tasks:  21%|███▌             | 331/1600 [3:03:00<34:17:44, 97.29s/it]

Processing tasks:  21%|███▌             | 332/1600 [3:04:25<32:57:53, 93.59s/it]

Processing tasks:  21%|███▌             | 333/1600 [3:06:17<34:55:30, 99.23s/it]

Processing tasks:  21%|███▎            | 334/1600 [3:08:02<35:28:26, 100.87s/it]

Processing tasks:  21%|███▌             | 335/1600 [3:09:20<33:02:15, 94.02s/it]

Processing tasks:  21%|███▌             | 336/1600 [3:10:40<31:34:31, 89.93s/it]

Processing tasks:  21%|███▌             | 337/1600 [3:12:15<32:04:07, 91.41s/it]

Processing tasks:  21%|███▌             | 338/1600 [3:13:45<31:53:14, 90.96s/it]

Processing tasks:  21%|███▌             | 339/1600 [3:15:20<32:18:09, 92.22s/it]

Processing tasks:  21%|███▌             | 340/1600 [3:17:06<33:39:03, 96.15s/it]

Processing tasks:  21%|███▌             | 341/1600 [3:18:35<32:57:01, 94.22s/it]

Processing tasks:  21%|███▋             | 342/1600 [3:19:53<31:07:55, 89.09s/it]

Processing tasks:  21%|███▋             | 343/1600 [3:21:07<29:35:32, 84.75s/it]

Processing tasks:  22%|███▋             | 344/1600 [3:22:35<29:55:07, 85.75s/it]

Processing tasks:  22%|███▋             | 345/1600 [3:23:51<28:49:55, 82.71s/it]

Processing tasks:  22%|███▋             | 346/1600 [3:24:59<27:15:33, 78.26s/it]

Processing tasks:  22%|███▋             | 347/1600 [3:26:18<27:19:44, 78.52s/it]

Processing tasks:  22%|███▋             | 348/1600 [3:27:23<25:55:45, 74.56s/it]

Processing tasks:  22%|███▋             | 349/1600 [3:28:30<25:05:04, 72.19s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  22%|███▋             | 350/1600 [3:29:36<24:27:19, 70.43s/it]

Processing tasks:  22%|███▋             | 351/1600 [3:31:02<25:59:27, 74.91s/it]

Processing tasks:  22%|███▋             | 352/1600 [3:32:09<25:14:31, 72.81s/it]

Processing tasks:  22%|███▊             | 353/1600 [3:33:23<25:15:36, 72.92s/it]

Processing tasks:  22%|███▊             | 354/1600 [3:34:41<25:49:05, 74.60s/it]

Processing tasks:  22%|███▊             | 355/1600 [3:35:50<25:13:35, 72.94s/it]

Processing tasks:  22%|███▊             | 356/1600 [3:37:32<28:14:08, 81.71s/it]

Processing tasks:  22%|███▊             | 357/1600 [3:38:51<27:52:34, 80.74s/it]

Processing tasks:  22%|███▊             | 358/1600 [3:40:23<29:01:58, 84.15s/it]

Processing tasks:  22%|███▊             | 359/1600 [3:41:54<29:40:34, 86.09s/it]

Processing tasks:  22%|███▊             | 360/1600 [3:43:04<28:01:12, 81.35s/it]

Processing tasks:  23%|███▊             | 361/1600 [3:44:53<30:49:12, 89.55s/it]

Processing tasks:  23%|███▊             | 362/1600 [3:46:07<29:16:44, 85.14s/it]

Processing tasks:  23%|███▊             | 363/1600 [3:47:12<27:09:29, 79.04s/it]

Processing tasks:  23%|███▊             | 364/1600 [3:48:56<29:43:11, 86.56s/it]

Processing tasks:  23%|███▉             | 365/1600 [3:50:43<31:43:12, 92.46s/it]

Processing tasks:  23%|███▉             | 366/1600 [3:52:14<31:33:35, 92.07s/it]

Processing tasks:  23%|███▉             | 367/1600 [3:54:05<33:32:18, 97.92s/it]

Processing tasks:  23%|███▋            | 368/1600 [3:55:54<34:37:47, 101.19s/it]

Processing tasks:  23%|███▋            | 369/1600 [3:57:32<34:18:05, 100.31s/it]

Processing tasks:  23%|███▋            | 370/1600 [3:59:12<34:10:46, 100.04s/it]

Processing tasks:  23%|███▉             | 371/1600 [4:00:42<33:11:30, 97.23s/it]

Processing tasks:  23%|███▉             | 372/1600 [4:01:45<29:37:33, 86.85s/it]

Processing tasks:  23%|███▉             | 373/1600 [4:03:00<28:20:01, 83.13s/it]

Processing tasks:  23%|███▉             | 374/1600 [4:04:29<28:57:29, 85.03s/it]

Processing tasks:  23%|███▉             | 375/1600 [4:05:56<29:08:09, 85.62s/it]

Processing tasks:  24%|███▉             | 376/1600 [4:07:37<30:38:14, 90.11s/it]

Processing tasks:  24%|████             | 377/1600 [4:09:24<32:24:46, 95.41s/it]

Processing tasks:  24%|████             | 378/1600 [4:11:13<33:44:31, 99.40s/it]

Processing tasks:  24%|███▊            | 379/1600 [4:12:58<34:16:33, 101.06s/it]

Processing tasks:  24%|███▊            | 380/1600 [4:14:40<34:23:38, 101.49s/it]

Processing tasks:  24%|███▊            | 381/1600 [4:16:30<35:10:00, 103.86s/it]

Processing tasks:  24%|███▊            | 382/1600 [4:18:20<35:48:36, 105.84s/it]

Processing tasks:  24%|████             | 383/1600 [4:19:46<33:46:40, 99.92s/it]

Processing tasks:  24%|████             | 384/1600 [4:21:18<32:53:37, 97.38s/it]

Processing tasks:  24%|███▊            | 385/1600 [4:23:07<34:01:20, 100.81s/it]

Processing tasks:  24%|████             | 386/1600 [4:24:21<31:20:16, 92.93s/it]

Processing tasks:  24%|████             | 387/1600 [4:26:07<32:38:09, 96.86s/it]

Processing tasks:  24%|████             | 388/1600 [4:27:46<32:45:09, 97.29s/it]

Processing tasks:  24%|████▏            | 389/1600 [4:29:25<32:56:35, 97.93s/it]

Processing tasks:  24%|████▏            | 390/1600 [4:31:05<33:08:10, 98.59s/it]

Processing tasks:  24%|████▏            | 391/1600 [4:32:24<31:06:34, 92.63s/it]

Processing tasks:  24%|████▏            | 392/1600 [4:34:06<32:04:38, 95.60s/it]

Processing tasks:  25%|████▏            | 393/1600 [4:35:27<30:30:54, 91.01s/it]

Processing tasks:  25%|████▏            | 394/1600 [4:37:17<32:27:54, 96.91s/it]

Processing tasks:  25%|████▏            | 395/1600 [4:38:48<31:49:42, 95.09s/it]

Processing tasks:  25%|████▏            | 396/1600 [4:40:14<30:52:36, 92.32s/it]

Processing tasks:  25%|████▏            | 397/1600 [4:41:55<31:43:43, 94.95s/it]

Processing tasks:  25%|████▏            | 398/1600 [4:43:39<32:33:57, 97.54s/it]

Processing tasks:  25%|████▏            | 399/1600 [4:45:11<32:03:17, 96.08s/it]

Processing tasks:  25%|████▎            | 400/1600 [4:46:59<33:07:58, 99.40s/it]

Processing tasks:  25%|████            | 401/1600 [4:48:45<33:49:05, 101.54s/it]

Processing tasks:  25%|████▎            | 402/1600 [4:50:07<31:50:44, 95.70s/it]

Processing tasks:  25%|████▎            | 403/1600 [4:51:29<30:23:37, 91.41s/it]

Processing tasks:  25%|████▎            | 404/1600 [4:53:04<30:47:14, 92.67s/it]

Processing tasks:  25%|████▎            | 405/1600 [4:54:17<28:46:06, 86.67s/it]

Processing tasks:  25%|████▎            | 406/1600 [4:55:33<27:40:39, 83.45s/it]

Processing tasks:  25%|████▎            | 407/1600 [4:56:50<27:04:22, 81.70s/it]

Processing tasks:  26%|████▎            | 408/1600 [4:58:38<29:40:09, 89.61s/it]

Processing tasks:  26%|████▎            | 409/1600 [5:00:00<28:51:59, 87.25s/it]

Processing tasks:  26%|████▎            | 410/1600 [5:01:27<28:50:30, 87.25s/it]

Processing tasks:  26%|████▎            | 411/1600 [5:03:04<29:42:54, 89.97s/it]

Processing tasks:  26%|████▍            | 412/1600 [5:04:50<31:20:08, 94.96s/it]

Processing tasks:  26%|████▍            | 413/1600 [5:06:22<31:01:10, 94.08s/it]

Processing tasks:  26%|████▍            | 414/1600 [5:07:55<30:52:07, 93.70s/it]

Processing tasks:  26%|████▍            | 415/1600 [5:09:27<30:41:48, 93.26s/it]

Processing tasks:  26%|████▍            | 416/1600 [5:11:15<32:07:14, 97.66s/it]

Processing tasks:  26%|████▏           | 417/1600 [5:13:04<33:11:39, 101.01s/it]

Processing tasks:  26%|████▏           | 418/1600 [5:14:54<33:59:09, 103.51s/it]

Processing tasks:  26%|████▍            | 419/1600 [5:16:20<32:16:58, 98.41s/it]

Processing tasks:  26%|████▏           | 420/1600 [5:18:11<33:28:36, 102.13s/it]

Processing tasks:  26%|████▍            | 421/1600 [5:19:39<32:01:44, 97.80s/it]

Processing tasks:  26%|████▏           | 422/1600 [5:21:27<33:04:57, 101.10s/it]

Processing tasks:  26%|████▏           | 423/1600 [5:23:06<32:48:46, 100.36s/it]

Processing tasks:  26%|████▏           | 424/1600 [5:24:48<32:57:00, 100.87s/it]

Processing tasks:  27%|████▌            | 425/1600 [5:26:15<31:35:10, 96.78s/it]

Processing tasks:  27%|████▌            | 426/1600 [5:27:37<30:05:12, 92.26s/it]

Processing tasks:  27%|████▌            | 427/1600 [5:29:10<30:06:14, 92.39s/it]

Processing tasks:  27%|████▌            | 428/1600 [5:30:38<29:42:11, 91.24s/it]

Processing tasks:  27%|████▌            | 429/1600 [5:32:01<28:53:33, 88.82s/it]

Processing tasks:  27%|████▌            | 430/1600 [5:33:23<28:07:57, 86.56s/it]

Processing tasks:  27%|████▌            | 431/1600 [5:34:46<27:44:51, 85.45s/it]

Processing tasks:  27%|████▌            | 432/1600 [5:36:11<27:43:42, 85.46s/it]

Processing tasks:  27%|████▌            | 433/1600 [5:37:36<27:38:46, 85.28s/it]

Processing tasks:  27%|████▌            | 434/1600 [5:38:57<27:14:56, 84.13s/it]

Processing tasks:  27%|████▌            | 435/1600 [5:40:27<27:45:27, 85.77s/it]

Processing tasks:  27%|████▋            | 436/1600 [5:41:42<26:38:54, 82.42s/it]

Processing tasks:  27%|████▋            | 437/1600 [5:43:27<28:48:57, 89.20s/it]

Processing tasks:  27%|████▋            | 438/1600 [5:45:13<30:30:01, 94.49s/it]

Processing tasks:  27%|████▋            | 439/1600 [5:46:59<31:30:03, 97.68s/it]

Processing tasks:  28%|████▍           | 440/1600 [5:48:45<32:19:31, 100.32s/it]

Processing tasks:  28%|████▋            | 441/1600 [5:50:11<30:55:46, 96.07s/it]

Processing tasks:  28%|████▋            | 442/1600 [5:51:35<29:44:29, 92.46s/it]

Processing tasks:  28%|████▋            | 443/1600 [5:53:06<29:30:40, 91.82s/it]

Processing tasks:  28%|████▋            | 444/1600 [5:54:32<28:55:27, 90.08s/it]

Processing tasks:  28%|████▋            | 445/1600 [5:55:51<27:53:19, 86.93s/it]

Processing tasks:  28%|████▋            | 446/1600 [5:57:23<28:22:40, 88.53s/it]

Processing tasks:  28%|████▋            | 447/1600 [5:58:45<27:42:06, 86.49s/it]

Processing tasks:  28%|████▊            | 448/1600 [6:00:07<27:16:07, 85.21s/it]

Processing tasks:  28%|████▊            | 449/1600 [6:01:32<27:13:07, 85.13s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  28%|████▊            | 450/1600 [6:02:58<27:15:53, 85.35s/it]

Processing tasks:  28%|████▊            | 451/1600 [6:04:24<27:18:02, 85.54s/it]

Processing tasks:  28%|████▊            | 452/1600 [6:05:49<27:13:42, 85.39s/it]

Processing tasks:  28%|████▊            | 453/1600 [6:07:20<27:42:06, 86.95s/it]

Processing tasks:  28%|████▊            | 454/1600 [6:08:30<26:04:01, 81.89s/it]

Processing tasks:  28%|████▊            | 455/1600 [6:09:55<26:20:36, 82.83s/it]

Processing tasks:  28%|████▊            | 456/1600 [6:11:25<27:00:13, 84.98s/it]

Processing tasks:  29%|████▊            | 457/1600 [6:12:46<26:39:34, 83.97s/it]

Processing tasks:  29%|████▊            | 458/1600 [6:14:09<26:30:11, 83.55s/it]

Processing tasks:  29%|████▉            | 459/1600 [6:15:28<26:05:16, 82.31s/it]

Processing tasks:  29%|████▉            | 460/1600 [6:16:53<26:18:17, 83.07s/it]

Processing tasks:  29%|████▉            | 461/1600 [6:18:19<26:32:23, 83.88s/it]

Processing tasks:  29%|████▉            | 462/1600 [6:19:42<26:25:07, 83.57s/it]

Processing tasks:  29%|████▉            | 463/1600 [6:21:07<26:34:41, 84.15s/it]

Processing tasks:  29%|████▉            | 464/1600 [6:22:37<27:03:45, 85.76s/it]

Processing tasks:  29%|████▉            | 465/1600 [6:24:03<27:01:31, 85.72s/it]

Processing tasks:  29%|████▉            | 466/1600 [6:25:23<26:27:45, 84.01s/it]

Processing tasks:  29%|████▉            | 467/1600 [6:26:37<25:33:41, 81.22s/it]

Processing tasks:  29%|████▉            | 468/1600 [6:28:07<26:19:38, 83.73s/it]

Processing tasks:  29%|████▉            | 469/1600 [6:29:20<25:17:03, 80.48s/it]

Processing tasks:  29%|████▉            | 470/1600 [6:30:28<24:08:26, 76.91s/it]

Processing tasks:  29%|█████            | 471/1600 [6:31:58<25:20:32, 80.81s/it]

Processing tasks:  30%|█████            | 472/1600 [6:33:18<25:15:53, 80.63s/it]

Processing tasks:  30%|█████            | 473/1600 [6:34:42<25:31:16, 81.52s/it]

Processing tasks:  30%|█████            | 474/1600 [6:36:13<26:21:08, 84.25s/it]

Processing tasks:  30%|█████            | 475/1600 [6:37:41<26:41:58, 85.44s/it]

Processing tasks:  30%|█████            | 476/1600 [6:39:11<27:09:14, 86.97s/it]

Processing tasks:  30%|█████            | 477/1600 [6:40:30<26:20:17, 84.43s/it]

Processing tasks:  30%|█████            | 478/1600 [6:41:57<26:32:38, 85.17s/it]

Processing tasks:  30%|█████            | 479/1600 [6:43:20<26:20:51, 84.61s/it]

Processing tasks:  30%|█████            | 480/1600 [6:44:43<26:10:17, 84.12s/it]

Processing tasks:  30%|█████            | 481/1600 [6:46:08<26:15:29, 84.48s/it]

Processing tasks:  30%|█████            | 482/1600 [6:47:32<26:07:19, 84.11s/it]

Processing tasks:  30%|█████▏           | 483/1600 [6:48:50<25:33:10, 82.35s/it]

Processing tasks:  30%|█████▏           | 484/1600 [6:50:20<26:12:33, 84.55s/it]

Processing tasks:  30%|█████▏           | 485/1600 [6:51:44<26:12:50, 84.64s/it]

Processing tasks:  30%|█████▏           | 486/1600 [6:53:12<26:27:15, 85.49s/it]

Processing tasks:  30%|█████▏           | 487/1600 [6:54:38<26:29:24, 85.68s/it]

Processing tasks:  30%|█████▏           | 488/1600 [6:56:01<26:12:17, 84.84s/it]

Processing tasks:  31%|█████▏           | 489/1600 [6:57:22<25:49:47, 83.70s/it]

Processing tasks:  31%|█████▏           | 490/1600 [6:58:46<25:51:37, 83.87s/it]

Processing tasks:  31%|█████▏           | 491/1600 [7:00:11<25:56:40, 84.22s/it]

Processing tasks:  31%|█████▏           | 492/1600 [7:01:40<26:21:46, 85.66s/it]

Processing tasks:  31%|█████▏           | 493/1600 [7:03:04<26:07:38, 84.97s/it]

Processing tasks:  31%|█████▏           | 494/1600 [7:04:38<26:58:07, 87.78s/it]

Processing tasks:  31%|█████▎           | 495/1600 [7:06:05<26:51:04, 87.48s/it]

Processing tasks:  31%|█████▎           | 496/1600 [7:07:33<26:54:59, 87.77s/it]

Processing tasks:  31%|█████▎           | 497/1600 [7:08:46<25:32:22, 83.36s/it]

Processing tasks:  31%|█████▎           | 498/1600 [7:09:53<23:58:05, 78.30s/it]

Processing tasks:  31%|█████▎           | 499/1600 [7:11:20<24:44:35, 80.90s/it]

Processing tasks:  31%|█████▎           | 500/1600 [7:12:39<24:36:01, 80.51s/it]

Processing tasks:  31%|█████▎           | 501/1600 [7:14:03<24:53:34, 81.54s/it]

Processing tasks:  31%|█████▎           | 502/1600 [7:15:32<25:32:33, 83.75s/it]

Processing tasks:  31%|█████▎           | 503/1600 [7:17:03<26:07:56, 85.76s/it]

Processing tasks:  32%|█████▎           | 504/1600 [7:18:31<26:21:10, 86.56s/it]

Processing tasks:  32%|█████▎           | 505/1600 [7:19:56<26:09:26, 86.00s/it]

Processing tasks:  32%|█████▍           | 506/1600 [7:21:27<26:37:08, 87.59s/it]

Processing tasks:  32%|█████▍           | 507/1600 [7:22:44<25:36:55, 84.37s/it]

Processing tasks:  32%|█████▍           | 508/1600 [7:24:08<25:32:17, 84.19s/it]

Processing tasks:  32%|█████▍           | 509/1600 [7:25:39<26:11:00, 86.40s/it]

Processing tasks:  32%|█████▍           | 510/1600 [7:27:04<25:58:14, 85.77s/it]

Processing tasks:  32%|█████▍           | 511/1600 [7:28:18<24:52:57, 82.26s/it]

Processing tasks:  32%|█████▍           | 512/1600 [7:29:48<25:34:25, 84.62s/it]

Processing tasks:  32%|█████▍           | 513/1600 [7:31:12<25:32:37, 84.60s/it]

Processing tasks:  32%|█████▍           | 514/1600 [7:32:36<25:28:41, 84.46s/it]

Processing tasks:  32%|█████▍           | 515/1600 [7:33:57<25:03:31, 83.14s/it]

Processing tasks:  32%|█████▍           | 516/1600 [7:35:21<25:09:38, 83.56s/it]

Processing tasks:  32%|█████▍           | 517/1600 [7:36:36<24:20:01, 80.89s/it]

Processing tasks:  32%|█████▌           | 518/1600 [7:38:02<24:48:34, 82.55s/it]

Processing tasks:  32%|█████▌           | 519/1600 [7:39:29<25:13:06, 83.98s/it]

Processing tasks:  32%|█████▌           | 520/1600 [7:40:39<23:54:31, 79.70s/it]

Processing tasks:  33%|█████▌           | 521/1600 [7:42:05<24:24:05, 81.41s/it]

Processing tasks:  33%|█████▌           | 522/1600 [7:43:33<24:59:29, 83.46s/it]

Processing tasks:  33%|█████▌           | 523/1600 [7:45:04<25:38:30, 85.71s/it]

Processing tasks:  33%|█████▌           | 524/1600 [7:46:27<25:25:25, 85.06s/it]

Processing tasks:  33%|█████▌           | 525/1600 [7:47:52<25:20:12, 84.85s/it]

Processing tasks:  33%|█████▌           | 526/1600 [7:49:15<25:08:34, 84.28s/it]

Processing tasks:  33%|█████▌           | 527/1600 [7:50:43<25:27:47, 85.43s/it]

Processing tasks:  33%|█████▌           | 528/1600 [7:52:30<27:25:12, 92.08s/it]

Processing tasks:  33%|█████▌           | 529/1600 [7:54:16<28:34:44, 96.06s/it]

Processing tasks:  33%|█████▋           | 530/1600 [7:56:02<29:27:41, 99.12s/it]

Processing tasks:  33%|█████▎          | 531/1600 [7:57:45<29:46:12, 100.25s/it]

Processing tasks:  33%|█████▋           | 532/1600 [7:59:08<28:14:10, 95.18s/it]

Processing tasks:  33%|█████▋           | 533/1600 [8:00:49<28:44:15, 96.96s/it]

Processing tasks:  33%|█████▋           | 534/1600 [8:02:35<29:31:14, 99.69s/it]

Processing tasks:  33%|█████▋           | 535/1600 [8:04:06<28:40:15, 96.92s/it]

Processing tasks:  34%|█████▎          | 536/1600 [8:05:54<29:36:51, 100.20s/it]

Processing tasks:  34%|█████▎          | 537/1600 [8:07:43<30:21:37, 102.82s/it]

Processing tasks:  34%|█████▍          | 538/1600 [8:09:25<30:19:56, 102.82s/it]

Processing tasks:  34%|█████▍          | 539/1600 [8:11:16<31:01:34, 105.27s/it]

Processing tasks:  34%|█████▍          | 540/1600 [8:13:06<31:25:12, 106.71s/it]

Processing tasks:  34%|█████▍          | 541/1600 [8:14:54<31:25:33, 106.83s/it]

Processing tasks:  34%|█████▍          | 542/1600 [8:16:38<31:11:12, 106.12s/it]

Processing tasks:  34%|█████▍          | 543/1600 [8:18:23<31:04:49, 105.86s/it]

Processing tasks:  34%|█████▍          | 544/1600 [8:20:11<31:11:14, 106.32s/it]

Processing tasks:  34%|█████▍          | 545/1600 [8:21:59<31:19:56, 106.92s/it]

Processing tasks:  34%|█████▍          | 546/1600 [8:23:47<31:25:46, 107.35s/it]

Processing tasks:  34%|█████▍          | 547/1600 [8:25:37<31:34:03, 107.92s/it]

Processing tasks:  34%|█████▍          | 548/1600 [8:27:26<31:39:18, 108.33s/it]

Processing tasks:  34%|█████▍          | 549/1600 [8:29:14<31:36:46, 108.28s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  34%|█████▌          | 550/1600 [8:31:05<31:50:02, 109.15s/it]

Processing tasks:  34%|█████▌          | 551/1600 [8:32:49<31:18:10, 107.43s/it]

Processing tasks:  34%|█████▌          | 552/1600 [8:34:26<30:25:08, 104.49s/it]

Processing tasks:  35%|█████▌          | 553/1600 [8:36:15<30:45:40, 105.77s/it]

Processing tasks:  35%|█████▌          | 554/1600 [8:38:04<31:00:58, 106.75s/it]

Processing tasks:  35%|█████▌          | 555/1600 [8:39:52<31:04:49, 107.07s/it]

Processing tasks:  35%|█████▌          | 556/1600 [8:41:42<31:18:11, 107.94s/it]

Processing tasks:  35%|█████▌          | 557/1600 [8:43:31<31:23:01, 108.32s/it]

Processing tasks:  35%|█████▉           | 558/1600 [8:44:29<27:00:52, 93.33s/it]

Processing tasks:  35%|█████▉           | 559/1600 [8:46:17<28:11:30, 97.49s/it]

Processing tasks:  35%|█████▉           | 560/1600 [8:47:26<25:45:56, 89.19s/it]

Processing tasks:  35%|█████▉           | 561/1600 [8:49:15<27:26:38, 95.09s/it]

Processing tasks:  35%|█████▉           | 562/1600 [8:51:03<28:28:47, 98.77s/it]

Processing tasks:  35%|█████▋          | 563/1600 [8:52:53<29:28:46, 102.34s/it]

Processing tasks:  35%|█████▋          | 564/1600 [8:54:32<29:07:13, 101.19s/it]

Processing tasks:  35%|█████▋          | 565/1600 [8:56:17<29:26:19, 102.40s/it]

Processing tasks:  35%|█████▋          | 566/1600 [8:58:05<29:55:14, 104.17s/it]

Processing tasks:  35%|█████▋          | 567/1600 [8:59:56<30:26:46, 106.11s/it]

Processing tasks:  36%|█████▋          | 568/1600 [9:01:44<30:36:08, 106.75s/it]

Processing tasks:  36%|█████▋          | 569/1600 [9:03:34<30:50:09, 107.67s/it]

Processing tasks:  36%|█████▋          | 570/1600 [9:05:23<30:55:07, 108.07s/it]

Processing tasks:  36%|█████▋          | 571/1600 [9:07:10<30:49:44, 107.86s/it]

Processing tasks:  36%|█████▋          | 572/1600 [9:08:59<30:53:26, 108.18s/it]

Processing tasks:  36%|█████▋          | 573/1600 [9:10:48<30:53:57, 108.31s/it]

Processing tasks:  36%|█████▋          | 574/1600 [9:12:37<30:56:39, 108.58s/it]

Processing tasks:  36%|█████▊          | 575/1600 [9:14:28<31:04:09, 109.12s/it]

Processing tasks:  36%|█████▊          | 576/1600 [9:16:15<30:54:52, 108.68s/it]

Processing tasks:  36%|█████▊          | 577/1600 [9:18:06<31:04:01, 109.33s/it]

Processing tasks:  36%|█████▊          | 578/1600 [9:19:56<31:03:29, 109.40s/it]

Processing tasks:  36%|█████▊          | 579/1600 [9:21:40<30:33:56, 107.77s/it]

Processing tasks:  36%|█████▊          | 580/1600 [9:23:23<30:07:26, 106.32s/it]

Processing tasks:  36%|█████▊          | 581/1600 [9:25:09<30:06:39, 106.38s/it]

Processing tasks:  36%|█████▊          | 582/1600 [9:26:59<30:23:23, 107.47s/it]

Processing tasks:  36%|█████▊          | 583/1600 [9:28:49<30:36:32, 108.35s/it]

Processing tasks:  36%|█████▊          | 584/1600 [9:30:39<30:39:19, 108.62s/it]

Processing tasks:  37%|█████▊          | 585/1600 [9:32:26<30:30:07, 108.18s/it]

Processing tasks:  37%|█████▊          | 586/1600 [9:34:10<30:07:00, 106.92s/it]

Processing tasks:  37%|█████▊          | 587/1600 [9:35:52<29:41:07, 105.50s/it]

Processing tasks:  37%|█████▉          | 588/1600 [9:37:39<29:49:09, 106.08s/it]

Processing tasks:  37%|█████▉          | 589/1600 [9:39:28<29:57:57, 106.70s/it]

Processing tasks:  37%|█████▉          | 590/1600 [9:41:15<29:57:42, 106.79s/it]

Processing tasks:  37%|█████▉          | 591/1600 [9:43:05<30:13:27, 107.84s/it]

Processing tasks:  37%|█████▉          | 592/1600 [9:44:53<30:12:16, 107.87s/it]

Processing tasks:  37%|█████▉          | 593/1600 [9:46:42<30:14:36, 108.12s/it]

Processing tasks:  37%|█████▉          | 594/1600 [9:48:29<30:07:21, 107.79s/it]

Processing tasks:  37%|█████▉          | 595/1600 [9:50:15<29:59:05, 107.41s/it]

Processing tasks:  37%|█████▉          | 596/1600 [9:52:03<29:58:02, 107.45s/it]

Processing tasks:  37%|█████▉          | 597/1600 [9:53:51<30:02:03, 107.80s/it]

Processing tasks:  37%|█████▉          | 598/1600 [9:55:38<29:55:35, 107.52s/it]

Processing tasks:  37%|█████▉          | 599/1600 [9:57:26<29:54:00, 107.53s/it]

Processing tasks:  38%|██████          | 600/1600 [9:58:54<28:15:50, 101.75s/it]

Processing tasks:  38%|██████          | 601/1600 [10:00:17<26:40:30, 96.13s/it]

Processing tasks:  38%|██████          | 602/1600 [10:01:43<25:47:11, 93.02s/it]

Processing tasks:  38%|██████          | 603/1600 [10:03:12<25:29:07, 92.02s/it]

Processing tasks:  38%|██████          | 604/1600 [10:04:37<24:49:50, 89.75s/it]

Processing tasks:  38%|██████          | 605/1600 [10:06:01<24:20:20, 88.06s/it]

Processing tasks:  38%|██████          | 606/1600 [10:07:24<23:55:21, 86.64s/it]

Processing tasks:  38%|██████          | 607/1600 [10:08:54<24:10:58, 87.67s/it]

Processing tasks:  38%|██████          | 608/1600 [10:10:17<23:43:55, 86.12s/it]

Processing tasks:  38%|██████          | 609/1600 [10:11:45<23:50:41, 86.62s/it]

Processing tasks:  38%|██████          | 610/1600 [10:13:10<23:44:54, 86.36s/it]

Processing tasks:  38%|██████          | 611/1600 [10:14:41<24:05:15, 87.68s/it]

Processing tasks:  38%|██████          | 612/1600 [10:16:05<23:43:30, 86.45s/it]

Processing tasks:  38%|██████▏         | 613/1600 [10:17:36<24:05:36, 87.88s/it]

Processing tasks:  38%|██████▏         | 614/1600 [10:18:57<23:32:16, 85.94s/it]

Processing tasks:  38%|██████▏         | 615/1600 [10:20:22<23:22:59, 85.46s/it]

Processing tasks:  38%|██████▏         | 616/1600 [10:21:47<23:21:43, 85.47s/it]

Processing tasks:  39%|██████▏         | 617/1600 [10:23:13<23:20:54, 85.51s/it]

Processing tasks:  39%|██████▏         | 618/1600 [10:24:57<24:52:14, 91.18s/it]

Processing tasks:  39%|██████▏         | 619/1600 [10:26:43<26:02:12, 95.55s/it]

Processing tasks:  39%|██████▏         | 620/1600 [10:28:19<26:00:32, 95.54s/it]

Processing tasks:  39%|██████▏         | 621/1600 [10:29:48<25:30:01, 93.77s/it]

Processing tasks:  39%|██████▏         | 622/1600 [10:31:17<25:05:55, 92.39s/it]

Processing tasks:  39%|██████▏         | 623/1600 [10:32:45<24:39:48, 90.88s/it]

Processing tasks:  39%|██████▏         | 624/1600 [10:34:16<24:38:49, 90.91s/it]

Processing tasks:  39%|██████▎         | 625/1600 [10:35:30<23:16:48, 85.96s/it]

Processing tasks:  39%|██████▎         | 626/1600 [10:36:49<22:40:42, 83.82s/it]

Processing tasks:  39%|██████▎         | 627/1600 [10:38:08<22:16:36, 82.42s/it]

Processing tasks:  39%|██████▎         | 628/1600 [10:39:09<20:31:29, 76.02s/it]

Processing tasks:  39%|██████▎         | 629/1600 [10:40:33<21:09:52, 78.47s/it]

Processing tasks:  39%|██████▎         | 630/1600 [10:42:04<22:06:52, 82.07s/it]

Processing tasks:  39%|██████▎         | 631/1600 [10:43:17<21:23:19, 79.46s/it]

Processing tasks:  40%|██████▎         | 632/1600 [10:44:31<20:53:30, 77.70s/it]

Processing tasks:  40%|██████▎         | 633/1600 [10:45:55<21:22:23, 79.57s/it]

Processing tasks:  40%|██████▎         | 634/1600 [10:47:26<22:20:10, 83.24s/it]

Processing tasks:  40%|██████▎         | 635/1600 [10:48:57<22:53:46, 85.42s/it]

Processing tasks:  40%|██████▎         | 636/1600 [10:50:22<22:49:45, 85.25s/it]

Processing tasks:  40%|██████▎         | 637/1600 [10:51:38<22:04:15, 82.51s/it]

Processing tasks:  40%|██████▍         | 638/1600 [10:52:54<21:31:24, 80.55s/it]

Processing tasks:  40%|██████▍         | 639/1600 [10:54:21<22:01:52, 82.53s/it]

Processing tasks:  40%|██████▍         | 640/1600 [10:55:49<22:25:48, 84.11s/it]

Processing tasks:  40%|██████▍         | 641/1600 [10:57:35<24:09:46, 90.70s/it]

Processing tasks:  40%|██████▍         | 642/1600 [10:59:10<24:28:01, 91.94s/it]

Processing tasks:  40%|██████▍         | 643/1600 [11:00:54<25:25:35, 95.65s/it]

Processing tasks:  40%|██████▍         | 644/1600 [11:02:41<26:16:42, 98.96s/it]

Processing tasks:  40%|██████         | 645/1600 [11:04:24<26:33:05, 100.09s/it]

Processing tasks:  40%|██████▍         | 646/1600 [11:05:55<25:48:43, 97.40s/it]

Processing tasks:  40%|██████▍         | 647/1600 [11:07:20<24:48:31, 93.72s/it]

Processing tasks:  40%|██████▍         | 648/1600 [11:09:06<25:48:45, 97.61s/it]

Processing tasks:  41%|██████▍         | 649/1600 [11:10:50<26:14:28, 99.34s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  41%|██████▌         | 650/1600 [11:12:24<25:50:13, 97.91s/it]

Processing tasks:  41%|██████▌         | 651/1600 [11:14:00<25:38:20, 97.26s/it]

Processing tasks:  41%|██████▌         | 652/1600 [11:15:33<25:13:53, 95.82s/it]

Processing tasks:  41%|██████▌         | 653/1600 [11:17:22<26:15:49, 99.84s/it]

Processing tasks:  41%|██████▌         | 654/1600 [11:18:51<25:22:11, 96.55s/it]

Processing tasks:  41%|██████▌         | 655/1600 [11:20:02<23:22:16, 89.03s/it]

Processing tasks:  41%|██████▌         | 656/1600 [11:21:50<24:50:24, 94.73s/it]

Processing tasks:  41%|██████▌         | 657/1600 [11:23:18<24:15:04, 92.58s/it]

Processing tasks:  41%|██████▌         | 658/1600 [11:25:06<25:26:03, 97.20s/it]

Processing tasks:  41%|██████▌         | 659/1600 [11:26:13<23:05:01, 88.31s/it]

Processing tasks:  41%|██████▌         | 660/1600 [11:28:01<24:33:34, 94.06s/it]

Processing tasks:  41%|██████▌         | 661/1600 [11:29:46<25:25:39, 97.49s/it]

Processing tasks:  41%|██████▌         | 662/1600 [11:31:16<24:48:35, 95.22s/it]

Processing tasks:  41%|██████▋         | 663/1600 [11:33:00<25:28:10, 97.86s/it]

Processing tasks:  42%|██████▋         | 664/1600 [11:34:43<25:48:43, 99.28s/it]

Processing tasks:  42%|██████▋         | 665/1600 [11:36:10<24:49:36, 95.59s/it]

Processing tasks:  42%|██████▋         | 666/1600 [11:37:57<25:43:25, 99.15s/it]

Processing tasks:  42%|██████▋         | 667/1600 [11:39:31<25:16:26, 97.52s/it]

Processing tasks:  42%|██████▋         | 668/1600 [11:41:08<25:11:42, 97.32s/it]

Processing tasks:  42%|██████▋         | 669/1600 [11:42:36<24:27:25, 94.57s/it]

Processing tasks:  42%|██████▋         | 670/1600 [11:44:23<25:25:24, 98.41s/it]

Processing tasks:  42%|██████▋         | 671/1600 [11:45:50<24:27:03, 94.75s/it]

Processing tasks:  42%|██████▋         | 672/1600 [11:47:37<25:24:30, 98.57s/it]

Processing tasks:  42%|██████▋         | 673/1600 [11:49:04<24:29:09, 95.09s/it]

Processing tasks:  42%|██████▋         | 674/1600 [11:50:44<24:51:45, 96.66s/it]

Processing tasks:  42%|██████▊         | 675/1600 [11:52:08<23:50:48, 92.81s/it]

Processing tasks:  42%|██████▊         | 676/1600 [11:53:55<24:56:07, 97.15s/it]

Processing tasks:  42%|██████▎        | 677/1600 [11:55:44<25:47:01, 100.56s/it]

Processing tasks:  42%|██████▎        | 678/1600 [11:57:28<26:00:37, 101.56s/it]

Processing tasks:  42%|██████▎        | 679/1600 [11:59:18<26:37:17, 104.06s/it]

Processing tasks:  42%|██████▍        | 680/1600 [12:01:05<26:50:29, 105.03s/it]

Processing tasks:  43%|██████▊         | 681/1600 [12:02:29<25:11:52, 98.71s/it]

Processing tasks:  43%|██████▍        | 682/1600 [12:04:19<26:00:04, 101.97s/it]

Processing tasks:  43%|██████▊         | 683/1600 [12:05:52<25:19:02, 99.39s/it]

Processing tasks:  43%|██████▍        | 684/1600 [12:07:35<25:32:12, 100.36s/it]

Processing tasks:  43%|██████▊         | 685/1600 [12:08:52<23:44:06, 93.38s/it]

Processing tasks:  43%|██████▊         | 686/1600 [12:10:34<24:23:12, 96.05s/it]

Processing tasks:  43%|██████▊         | 687/1600 [12:12:21<25:13:05, 99.44s/it]

Processing tasks:  43%|██████▉         | 688/1600 [12:13:55<24:46:23, 97.79s/it]

Processing tasks:  43%|██████▉         | 689/1600 [12:15:28<24:21:19, 96.24s/it]

Processing tasks:  43%|██████▉         | 690/1600 [12:17:11<24:51:07, 98.32s/it]

Processing tasks:  43%|██████▍        | 691/1600 [12:18:58<25:30:26, 101.02s/it]

Processing tasks:  43%|██████▍        | 692/1600 [12:20:48<26:05:59, 103.48s/it]

Processing tasks:  43%|██████▉         | 693/1600 [12:22:03<23:57:47, 95.11s/it]

Processing tasks:  43%|██████▉         | 694/1600 [12:23:50<24:49:29, 98.64s/it]

Processing tasks:  43%|██████▉         | 695/1600 [12:25:31<25:00:14, 99.46s/it]

Processing tasks:  44%|██████▌        | 696/1600 [12:27:19<25:37:31, 102.05s/it]

Processing tasks:  44%|██████▉         | 697/1600 [12:28:50<24:45:22, 98.70s/it]

Processing tasks:  44%|██████▉         | 698/1600 [12:30:22<24:10:25, 96.48s/it]

Processing tasks:  44%|██████▉         | 699/1600 [12:32:03<24:28:59, 97.82s/it]

Processing tasks:  44%|██████▌        | 700/1600 [12:33:49<25:03:37, 100.24s/it]

Processing tasks:  44%|██████▌        | 701/1600 [12:35:37<25:37:49, 102.64s/it]

Processing tasks:  44%|██████▌        | 702/1600 [12:37:23<25:53:28, 103.80s/it]

Processing tasks:  44%|██████▌        | 703/1600 [12:39:12<26:15:30, 105.39s/it]

Processing tasks:  44%|███████         | 704/1600 [12:40:38<24:43:27, 99.34s/it]

Processing tasks:  44%|██████▌        | 705/1600 [12:42:26<25:21:01, 101.97s/it]

Processing tasks:  44%|███████         | 706/1600 [12:43:51<24:04:10, 96.92s/it]

Processing tasks:  44%|███████         | 707/1600 [12:45:14<22:59:29, 92.69s/it]

Processing tasks:  44%|███████         | 708/1600 [12:46:49<23:07:56, 93.36s/it]

Processing tasks:  44%|███████         | 709/1600 [12:48:36<24:10:19, 97.66s/it]

Processing tasks:  44%|███████         | 710/1600 [12:50:01<23:11:24, 93.80s/it]

Processing tasks:  44%|███████         | 711/1600 [12:51:50<24:17:27, 98.37s/it]

Processing tasks:  44%|███████         | 712/1600 [12:53:18<23:30:39, 95.31s/it]

Processing tasks:  45%|███████▏        | 713/1600 [12:55:07<24:26:43, 99.21s/it]

Processing tasks:  45%|███████▏        | 714/1600 [12:56:20<22:32:28, 91.59s/it]

Processing tasks:  45%|███████▏        | 715/1600 [12:57:58<22:57:42, 93.40s/it]

Processing tasks:  45%|███████▏        | 716/1600 [12:59:34<23:06:37, 94.11s/it]

Processing tasks:  45%|███████▏        | 717/1600 [13:01:05<22:52:59, 93.29s/it]

Processing tasks:  45%|███████▏        | 718/1600 [13:02:31<22:17:33, 90.99s/it]

Processing tasks:  45%|███████▏        | 719/1600 [13:04:19<23:32:16, 96.18s/it]

Processing tasks:  45%|███████▏        | 720/1600 [13:05:56<23:33:20, 96.36s/it]

Processing tasks:  45%|███████▏        | 721/1600 [13:07:42<24:16:23, 99.41s/it]

Processing tasks:  45%|███████▏        | 722/1600 [13:09:11<23:26:18, 96.10s/it]

Processing tasks:  45%|███████▏        | 723/1600 [13:10:58<24:13:51, 99.47s/it]

Processing tasks:  45%|██████▊        | 724/1600 [13:12:46<24:50:33, 102.09s/it]

Processing tasks:  45%|██████▊        | 725/1600 [13:14:32<25:05:56, 103.27s/it]

Processing tasks:  45%|██████▊        | 726/1600 [13:16:20<25:22:25, 104.51s/it]

Processing tasks:  45%|██████▊        | 727/1600 [13:17:53<24:29:42, 101.01s/it]

Processing tasks:  46%|██████▊        | 728/1600 [13:19:33<24:25:13, 100.82s/it]

Processing tasks:  46%|███████▎        | 729/1600 [13:21:10<24:08:11, 99.76s/it]

Processing tasks:  46%|██████▊        | 730/1600 [13:22:57<24:38:29, 101.96s/it]

Processing tasks:  46%|███████▎        | 731/1600 [13:24:17<22:57:44, 95.13s/it]

Processing tasks:  46%|███████▎        | 732/1600 [13:25:45<22:26:55, 93.11s/it]

Processing tasks:  46%|███████▎        | 733/1600 [13:27:30<23:16:25, 96.64s/it]

Processing tasks:  46%|███████▎        | 734/1600 [13:29:17<24:00:51, 99.83s/it]

Processing tasks:  46%|███████▎        | 735/1600 [13:30:54<23:47:35, 99.02s/it]

Processing tasks:  46%|███████▎        | 736/1600 [13:32:28<23:23:40, 97.48s/it]

Processing tasks:  46%|██████▉        | 737/1600 [13:34:16<24:05:53, 100.53s/it]

Processing tasks:  46%|██████▉        | 738/1600 [13:36:04<24:37:35, 102.85s/it]

Processing tasks:  46%|███████▍        | 739/1600 [13:37:37<23:54:11, 99.94s/it]

Processing tasks:  46%|███████▍        | 740/1600 [13:39:00<22:38:55, 94.81s/it]

Processing tasks:  46%|███████▍        | 741/1600 [13:40:47<23:31:35, 98.60s/it]

Processing tasks:  46%|███████▍        | 742/1600 [13:42:04<21:55:16, 91.98s/it]

Processing tasks:  46%|███████▍        | 743/1600 [13:43:37<21:58:49, 92.33s/it]

Processing tasks:  46%|███████▍        | 744/1600 [13:45:16<22:25:00, 94.28s/it]

Processing tasks:  47%|███████▍        | 745/1600 [13:47:04<23:22:57, 98.45s/it]

Processing tasks:  47%|██████▉        | 746/1600 [13:48:51<23:59:01, 101.10s/it]

Processing tasks:  47%|███████▍        | 747/1600 [13:50:13<22:32:58, 95.17s/it]

Processing tasks:  47%|███████▍        | 748/1600 [13:51:27<21:01:28, 88.84s/it]

Processing tasks:  47%|███████▍        | 749/1600 [13:53:17<22:30:44, 95.23s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  47%|███████▌        | 750/1600 [13:55:08<23:35:56, 99.95s/it]

Processing tasks:  47%|███████        | 751/1600 [13:56:56<24:10:50, 102.53s/it]

Processing tasks:  47%|███████▌        | 752/1600 [13:58:18<22:38:37, 96.13s/it]

Processing tasks:  47%|███████▌        | 753/1600 [13:59:56<22:47:14, 96.85s/it]

Processing tasks:  47%|███████▌        | 754/1600 [14:01:23<22:03:48, 93.89s/it]

Processing tasks:  47%|███████▌        | 755/1600 [14:02:46<21:14:05, 90.47s/it]

Processing tasks:  47%|███████▌        | 756/1600 [14:04:34<22:30:08, 95.98s/it]

Processing tasks:  47%|███████▌        | 757/1600 [14:06:14<22:41:35, 96.91s/it]

Processing tasks:  47%|███████▌        | 758/1600 [14:07:53<22:50:12, 97.64s/it]

Processing tasks:  47%|███████▌        | 759/1600 [14:09:28<22:38:46, 96.94s/it]

Processing tasks:  48%|███████▌        | 760/1600 [14:11:06<22:42:28, 97.32s/it]

Processing tasks:  48%|███████▌        | 761/1600 [14:12:33<21:57:32, 94.22s/it]

Processing tasks:  48%|███████▌        | 762/1600 [14:14:10<22:03:49, 94.78s/it]

Processing tasks:  48%|███████▋        | 763/1600 [14:15:57<22:54:32, 98.53s/it]

Processing tasks:  48%|███████▋        | 764/1600 [14:17:30<22:32:10, 97.05s/it]

Processing tasks:  48%|███████▏       | 765/1600 [14:19:18<23:15:25, 100.27s/it]

Processing tasks:  48%|███████▋        | 766/1600 [14:20:51<22:41:55, 97.98s/it]

Processing tasks:  48%|███████▋        | 767/1600 [14:22:25<22:22:50, 96.72s/it]

Processing tasks:  48%|███████▏       | 768/1600 [14:24:13<23:09:12, 100.18s/it]

Processing tasks:  48%|███████▏       | 769/1600 [14:25:56<23:19:13, 101.03s/it]

Processing tasks:  48%|███████▏       | 770/1600 [14:27:45<23:50:02, 103.38s/it]

Processing tasks:  48%|███████▋        | 771/1600 [14:29:16<22:56:21, 99.62s/it]

Processing tasks:  48%|███████▏       | 772/1600 [14:31:06<23:40:13, 102.92s/it]

Processing tasks:  48%|███████▋        | 773/1600 [14:32:38<22:51:28, 99.50s/it]

Processing tasks:  48%|███████▋        | 774/1600 [14:34:05<22:00:45, 95.94s/it]

Processing tasks:  48%|███████▎       | 775/1600 [14:35:55<22:55:44, 100.05s/it]

Processing tasks:  48%|███████▎       | 776/1600 [14:37:44<23:31:28, 102.78s/it]

Processing tasks:  49%|███████▎       | 777/1600 [14:39:36<24:07:42, 105.54s/it]

Processing tasks:  49%|███████▎       | 778/1600 [14:41:22<24:07:06, 105.63s/it]

Processing tasks:  49%|███████▎       | 779/1600 [14:42:58<23:27:44, 102.88s/it]

Processing tasks:  49%|███████▎       | 780/1600 [14:44:47<23:49:12, 104.58s/it]

Processing tasks:  49%|███████▎       | 781/1600 [14:46:22<23:06:43, 101.59s/it]

Processing tasks:  49%|███████▊        | 782/1600 [14:47:47<22:00:03, 96.83s/it]

Processing tasks:  49%|███████▊        | 783/1600 [14:49:27<22:08:52, 97.59s/it]

Processing tasks:  49%|███████▊        | 784/1600 [14:51:06<22:12:38, 97.99s/it]

Processing tasks:  49%|███████▊        | 785/1600 [14:52:48<22:29:30, 99.35s/it]

Processing tasks:  49%|███████▎       | 786/1600 [14:54:34<22:56:08, 101.44s/it]

Processing tasks:  49%|███████▍       | 787/1600 [14:56:21<23:16:28, 103.06s/it]

Processing tasks:  49%|███████▍       | 788/1600 [14:58:08<23:29:45, 104.17s/it]

Processing tasks:  49%|███████▍       | 789/1600 [14:59:47<23:06:29, 102.58s/it]

Processing tasks:  49%|███████▉        | 790/1600 [15:01:06<21:31:00, 95.63s/it]

Processing tasks:  49%|███████▉        | 791/1600 [15:02:40<21:22:15, 95.10s/it]

Processing tasks:  50%|███████▉        | 792/1600 [15:04:05<20:38:04, 91.94s/it]

Processing tasks:  50%|███████▉        | 793/1600 [15:05:51<21:33:04, 96.14s/it]

Processing tasks:  50%|███████▉        | 794/1600 [15:07:38<22:18:26, 99.64s/it]

Processing tasks:  50%|███████▉        | 795/1600 [15:09:05<21:23:46, 95.68s/it]

Processing tasks:  50%|███████▉        | 796/1600 [15:10:27<20:28:59, 91.72s/it]

Processing tasks:  50%|███████▉        | 797/1600 [15:12:15<21:30:00, 96.39s/it]

Processing tasks:  50%|███████▉        | 798/1600 [15:13:59<22:00:39, 98.80s/it]

Processing tasks:  50%|███████▍       | 799/1600 [15:15:49<22:43:38, 102.15s/it]

Processing tasks:  50%|███████▌       | 800/1600 [15:17:32<22:44:35, 102.34s/it]

Processing tasks:  50%|████████        | 801/1600 [15:19:02<21:55:45, 98.80s/it]

Processing tasks:  50%|████████        | 802/1600 [15:20:27<20:55:47, 94.42s/it]

Processing tasks:  50%|████████        | 803/1600 [15:22:04<21:06:24, 95.34s/it]

Processing tasks:  50%|████████        | 804/1600 [15:23:51<21:52:37, 98.94s/it]

Processing tasks:  50%|████████        | 805/1600 [15:25:32<21:58:36, 99.52s/it]

Processing tasks:  50%|████████        | 806/1600 [15:26:42<19:58:57, 90.60s/it]

Processing tasks:  50%|████████        | 807/1600 [15:28:31<21:10:09, 96.10s/it]

Processing tasks:  50%|████████        | 808/1600 [15:29:52<20:09:54, 91.66s/it]

Processing tasks:  51%|████████        | 809/1600 [15:31:18<19:45:25, 89.92s/it]

Processing tasks:  51%|████████        | 810/1600 [15:33:07<20:59:26, 95.65s/it]

Processing tasks:  51%|████████        | 811/1600 [15:34:56<21:50:05, 99.63s/it]

Processing tasks:  51%|███████▌       | 812/1600 [15:36:38<21:57:29, 100.32s/it]

Processing tasks:  51%|███████▌       | 813/1600 [15:38:27<22:28:59, 102.85s/it]

Processing tasks:  51%|███████▋       | 814/1600 [15:40:01<21:53:55, 100.30s/it]

Processing tasks:  51%|████████▏       | 815/1600 [15:41:37<21:36:33, 99.10s/it]

Processing tasks:  51%|███████▋       | 816/1600 [15:43:27<22:16:23, 102.27s/it]

Processing tasks:  51%|███████▋       | 817/1600 [15:45:16<22:39:58, 104.21s/it]

Processing tasks:  51%|███████▋       | 818/1600 [15:47:03<22:51:15, 105.21s/it]

Processing tasks:  51%|███████▋       | 819/1600 [15:48:51<22:57:02, 105.79s/it]

Processing tasks:  51%|████████▏       | 820/1600 [15:50:14<21:27:13, 99.02s/it]

Processing tasks:  51%|███████▋       | 821/1600 [15:52:03<22:05:50, 102.12s/it]

Processing tasks:  51%|████████▏       | 822/1600 [15:52:59<19:03:08, 88.16s/it]

Processing tasks:  51%|████████▏       | 823/1600 [15:54:22<18:44:26, 86.83s/it]

Processing tasks:  52%|████████▏       | 824/1600 [15:55:32<17:34:44, 81.55s/it]

Processing tasks:  52%|████████▎       | 825/1600 [15:57:06<18:22:22, 85.34s/it]

Processing tasks:  52%|████████▎       | 826/1600 [15:58:53<19:45:13, 91.88s/it]

Processing tasks:  52%|████████▎       | 827/1600 [16:00:27<19:53:10, 92.61s/it]

Processing tasks:  52%|████████▎       | 828/1600 [16:02:17<20:57:59, 97.77s/it]

Processing tasks:  52%|████████▎       | 829/1600 [16:03:36<19:45:21, 92.25s/it]

Processing tasks:  52%|████████▎       | 830/1600 [16:05:24<20:41:59, 96.78s/it]

Processing tasks:  52%|████████▎       | 831/1600 [16:07:00<20:38:21, 96.62s/it]

Processing tasks:  52%|████████▎       | 832/1600 [16:08:47<21:15:30, 99.65s/it]

Processing tasks:  52%|███████▊       | 833/1600 [16:10:33<21:39:16, 101.64s/it]

Processing tasks:  52%|███████▊       | 834/1600 [16:12:21<22:00:21, 103.42s/it]

Processing tasks:  52%|███████▊       | 835/1600 [16:14:00<21:41:31, 102.08s/it]

Processing tasks:  52%|███████▊       | 836/1600 [16:15:48<22:05:44, 104.12s/it]

Processing tasks:  52%|███████▊       | 837/1600 [16:17:36<22:17:51, 105.20s/it]

Processing tasks:  52%|███████▊       | 838/1600 [16:19:25<22:28:50, 106.21s/it]

Processing tasks:  52%|███████▊       | 839/1600 [16:21:14<22:39:22, 107.18s/it]

Processing tasks:  52%|███████▉       | 840/1600 [16:23:04<22:47:27, 107.96s/it]

Processing tasks:  53%|████████▍       | 841/1600 [16:23:59<19:23:12, 91.95s/it]

Processing tasks:  53%|████████▍       | 842/1600 [16:25:48<20:28:03, 97.21s/it]

Processing tasks:  53%|███████▉       | 843/1600 [16:27:37<21:10:25, 100.69s/it]

Processing tasks:  53%|███████▉       | 844/1600 [16:29:26<21:42:09, 103.35s/it]

Processing tasks:  53%|███████▉       | 845/1600 [16:31:00<21:03:52, 100.44s/it]

Processing tasks:  53%|███████▉       | 846/1600 [16:32:47<21:26:39, 102.39s/it]

Processing tasks:  53%|███████▉       | 847/1600 [16:34:32<21:33:53, 103.10s/it]

Processing tasks:  53%|███████▉       | 848/1600 [16:36:21<21:54:00, 104.84s/it]

Processing tasks:  53%|███████▉       | 849/1600 [16:38:10<22:07:45, 106.08s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  53%|███████▉       | 850/1600 [16:40:00<22:22:01, 107.36s/it]

Processing tasks:  53%|███████▉       | 851/1600 [16:41:36<21:36:49, 103.88s/it]

Processing tasks:  53%|███████▉       | 852/1600 [16:43:13<21:09:14, 101.81s/it]

Processing tasks:  53%|███████▉       | 853/1600 [16:45:02<21:34:20, 103.96s/it]

Processing tasks:  53%|████████       | 854/1600 [16:46:38<21:05:05, 101.75s/it]

Processing tasks:  53%|████████       | 855/1600 [16:48:27<21:31:08, 103.98s/it]

Processing tasks:  54%|████████       | 856/1600 [16:50:17<21:49:44, 105.62s/it]

Processing tasks:  54%|████████       | 857/1600 [16:52:07<22:02:56, 106.83s/it]

Processing tasks:  54%|████████       | 858/1600 [16:53:54<22:02:23, 106.93s/it]

Processing tasks:  54%|████████       | 859/1600 [16:55:42<22:04:53, 107.28s/it]

Processing tasks:  54%|████████       | 860/1600 [16:57:30<22:05:04, 107.44s/it]

Processing tasks:  54%|████████       | 861/1600 [16:59:02<21:05:42, 102.76s/it]

Processing tasks:  54%|████████       | 862/1600 [17:00:51<21:28:50, 104.78s/it]

Processing tasks:  54%|████████       | 863/1600 [17:02:41<21:45:50, 106.31s/it]

Processing tasks:  54%|████████       | 864/1600 [17:04:30<21:54:16, 107.14s/it]

Processing tasks:  54%|████████       | 865/1600 [17:06:19<21:58:28, 107.63s/it]

Processing tasks:  54%|████████       | 866/1600 [17:08:06<21:54:46, 107.48s/it]

Processing tasks:  54%|████████▏      | 867/1600 [17:09:55<21:58:08, 107.90s/it]

Processing tasks:  54%|████████▏      | 868/1600 [17:11:42<21:53:27, 107.66s/it]

Processing tasks:  54%|████████▏      | 869/1600 [17:13:29<21:49:48, 107.51s/it]

Processing tasks:  54%|████████▏      | 870/1600 [17:15:15<21:44:01, 107.18s/it]

Processing tasks:  54%|████████▏      | 871/1600 [17:16:56<21:16:42, 105.08s/it]

Processing tasks:  55%|████████▋       | 872/1600 [17:18:22<20:06:55, 99.47s/it]

Processing tasks:  55%|████████▏      | 873/1600 [17:20:11<20:39:21, 102.29s/it]

Processing tasks:  55%|████████▏      | 874/1600 [17:21:59<20:58:36, 104.02s/it]

Processing tasks:  55%|████████▏      | 875/1600 [17:23:45<21:05:24, 104.72s/it]

Processing tasks:  55%|████████▏      | 876/1600 [17:25:28<20:55:09, 104.02s/it]

Processing tasks:  55%|████████▏      | 877/1600 [17:27:15<21:07:20, 105.17s/it]

Processing tasks:  55%|████████▏      | 878/1600 [17:29:06<21:24:58, 106.78s/it]

Processing tasks:  55%|████████▏      | 879/1600 [17:30:54<21:29:02, 107.27s/it]

Processing tasks:  55%|████████▎      | 880/1600 [17:32:41<21:24:03, 107.00s/it]

Processing tasks:  55%|████████▎      | 881/1600 [17:34:29<21:28:00, 107.48s/it]

Processing tasks:  55%|████████▎      | 882/1600 [17:36:18<21:29:01, 107.72s/it]

Processing tasks:  55%|████████▎      | 883/1600 [17:38:07<21:33:27, 108.24s/it]

Processing tasks:  55%|████████▎      | 884/1600 [17:39:56<21:34:37, 108.49s/it]

Processing tasks:  55%|████████▎      | 885/1600 [17:41:46<21:36:04, 108.76s/it]

Processing tasks:  55%|████████▎      | 886/1600 [17:43:34<21:32:03, 108.58s/it]

Processing tasks:  55%|████████▎      | 887/1600 [17:44:57<19:59:01, 100.90s/it]

Processing tasks:  56%|████████▎      | 888/1600 [17:46:38<19:57:16, 100.89s/it]

Processing tasks:  56%|████████▎      | 889/1600 [17:48:27<20:25:00, 103.38s/it]

Processing tasks:  56%|████████▎      | 890/1600 [17:50:16<20:43:06, 105.05s/it]

Processing tasks:  56%|████████▎      | 891/1600 [17:52:05<20:57:31, 106.42s/it]

Processing tasks:  56%|████████▎      | 892/1600 [17:53:54<21:04:28, 107.16s/it]

Processing tasks:  56%|████████▎      | 893/1600 [17:55:42<21:03:25, 107.22s/it]

Processing tasks:  56%|████████▍      | 894/1600 [17:57:31<21:08:15, 107.78s/it]

Processing tasks:  56%|████████▍      | 895/1600 [17:59:21<21:14:04, 108.43s/it]

Processing tasks:  56%|████████▍      | 896/1600 [18:01:09<21:10:44, 108.30s/it]

Processing tasks:  56%|████████▍      | 897/1600 [18:02:55<21:03:03, 107.80s/it]

Processing tasks:  56%|████████▍      | 898/1600 [18:04:42<20:57:04, 107.44s/it]

Processing tasks:  56%|████████▍      | 899/1600 [18:06:35<21:13:34, 109.01s/it]

Processing tasks:  56%|████████▍      | 900/1600 [18:08:23<21:09:17, 108.80s/it]

Processing tasks:  56%|████████▍      | 901/1600 [18:10:11<21:06:24, 108.71s/it]

Processing tasks:  56%|████████▍      | 902/1600 [18:11:47<20:18:29, 104.74s/it]

Processing tasks:  56%|████████▍      | 903/1600 [18:13:35<20:27:52, 105.70s/it]

Processing tasks:  56%|████████▍      | 904/1600 [18:15:24<20:37:37, 106.69s/it]

Processing tasks:  57%|████████▍      | 906/1600 [18:19:00<20:42:07, 107.39s/it]

Processing tasks:  57%|████████▌      | 907/1600 [18:20:47<20:38:44, 107.25s/it]

Processing tasks:  57%|████████▌      | 909/1600 [18:24:13<20:08:26, 104.93s/it]

Processing tasks:  57%|████████▌      | 910/1600 [18:26:02<20:21:15, 106.20s/it]

Processing tasks:  57%|████████▌      | 912/1600 [18:29:35<20:21:39, 106.54s/it]

Processing tasks:  57%|████████▌      | 913/1600 [18:31:24<20:29:12, 107.35s/it]

Processing tasks:  57%|████████▌      | 915/1600 [18:35:03<20:35:08, 108.19s/it]

Processing tasks:  57%|████████▌      | 916/1600 [18:36:53<20:39:01, 108.69s/it]

Processing tasks:  57%|████████▌      | 918/1600 [18:40:20<20:01:01, 105.66s/it]

Processing tasks:  57%|████████▌      | 919/1600 [18:42:09<20:10:33, 106.66s/it]

Processing tasks:  57%|████████▋      | 920/1600 [18:43:59<20:20:51, 107.72s/it]

Processing tasks:  58%|████████▋      | 921/1600 [18:45:48<20:21:44, 107.96s/it]

Processing tasks:  58%|████████▋      | 922/1600 [18:47:35<20:17:17, 107.73s/it]

Processing tasks:  58%|████████▋      | 923/1600 [18:49:24<20:20:25, 108.16s/it]

Processing tasks:  58%|████████▋      | 924/1600 [18:51:14<20:26:16, 108.84s/it]

Processing tasks:  58%|████████▋      | 925/1600 [18:53:03<20:22:20, 108.65s/it]

Processing tasks:  58%|████████▋      | 926/1600 [18:54:51<20:18:27, 108.47s/it]

Processing tasks:  58%|████████▋      | 927/1600 [18:56:38<20:12:03, 108.06s/it]

Processing tasks:  58%|████████▋      | 928/1600 [18:58:28<20:16:27, 108.61s/it]

Processing tasks:  58%|█████████▎      | 929/1600 [18:59:44<18:26:51, 98.97s/it]

Processing tasks:  58%|████████▋      | 930/1600 [19:01:33<18:56:57, 101.82s/it]

Processing tasks:  58%|████████▋      | 931/1600 [19:03:20<19:14:04, 103.50s/it]

Processing tasks:  58%|████████▋      | 932/1600 [19:04:58<18:54:24, 101.89s/it]

Processing tasks:  58%|████████▋      | 933/1600 [19:06:44<19:04:41, 102.97s/it]

Processing tasks:  58%|████████▊      | 934/1600 [19:08:33<19:23:13, 104.80s/it]

Processing tasks:  58%|████████▊      | 935/1600 [19:10:22<19:34:52, 106.00s/it]

Processing tasks:  58%|████████▊      | 936/1600 [19:12:08<19:33:49, 106.07s/it]

Processing tasks:  59%|████████▊      | 937/1600 [19:13:55<19:37:05, 106.52s/it]

Processing tasks:  59%|████████▊      | 938/1600 [19:15:43<19:39:41, 106.92s/it]

Processing tasks:  59%|████████▊      | 939/1600 [19:17:32<19:45:31, 107.61s/it]

Processing tasks:  59%|████████▊      | 941/1600 [19:21:09<19:44:56, 107.89s/it]

Processing tasks:  59%|████████▊      | 942/1600 [19:22:50<19:20:03, 105.78s/it]

Processing tasks:  59%|████████▊      | 944/1600 [19:26:24<19:26:31, 106.69s/it]

Processing tasks:  59%|████████▊      | 945/1600 [19:28:03<18:57:46, 104.22s/it]

Processing tasks:  59%|████████▉      | 947/1600 [19:31:37<19:13:35, 106.00s/it]

Processing tasks:  59%|████████▉      | 948/1600 [19:33:24<19:13:44, 106.17s/it]

Submitting batch of 100 predictions to Label Studio...

Successfully submitted 100 predictions from batch to Label Studio.
Processing tasks:  59%|████████▉      | 950/1600 [19:36:51<18:53:00, 104.59s/it]

Processing tasks:  59%|████████▉      | 951/1600 [19:38:39<19:03:38, 105.73s/it]

Processing tasks:  60%|████████▉      | 953/1600 [19:42:18<19:19:47, 107.55s/it]

Processing tasks:  60%|████████▉      | 954/1600 [19:44:07<19:21:43, 107.90s/it]

Processing tasks:  60%|█████████▌      | 956/1600 [19:46:40<15:53:50, 88.87s/it]

Processing tasks:  60%|█████████▌      | 957/1600 [19:48:28<16:52:34, 94.49s/it]

Processing tasks:  60%|█████████▌      | 958/1600 [19:50:15<17:32:02, 98.32s/it]

Processing tasks:  60%|████████▉      | 959/1600 [19:52:04<18:05:28, 101.60s/it]

Processing tasks:  60%|█████████      | 960/1600 [19:53:51<18:19:45, 103.10s/it]

Processing tasks:  60%|█████████      | 961/1600 [19:55:38<18:31:34, 104.37s/it]

Processing tasks:  60%|█████████      | 962/1600 [19:57:25<18:37:51, 105.13s/it]

Processing tasks:  60%|█████████      | 963/1600 [19:59:15<18:50:13, 106.46s/it]

Processing tasks:  60%|█████████      | 965/1600 [20:02:52<18:56:54, 107.42s/it]

Processing tasks:  60%|█████████      | 966/1600 [20:04:42<19:03:34, 108.22s/it]

Processing tasks:  60%|█████████      | 968/1600 [20:08:16<18:53:34, 107.62s/it]

Processing tasks:  61%|█████████      | 969/1600 [20:10:04<18:52:22, 107.67s/it]

Processing tasks:  61%|█████████      | 971/1600 [20:13:41<18:52:51, 108.06s/it]

Processing tasks:  61%|█████████      | 972/1600 [20:15:28<18:49:16, 107.89s/it]

Processing tasks:  61%|█████████▏     | 974/1600 [20:18:58<18:23:52, 105.80s/it]

Processing tasks:  61%|█████████▏     | 975/1600 [20:20:46<18:27:44, 106.34s/it]

Processing tasks:  61%|█████████▏     | 977/1600 [20:24:23<18:37:55, 107.67s/it]

Processing tasks:  61%|█████████▏     | 978/1600 [20:26:12<18:39:57, 108.03s/it]

Processing tasks:  61%|█████████▏     | 979/1600 [20:27:59<18:34:22, 107.67s/it]

Processing tasks:  61%|█████████▏     | 980/1600 [20:29:48<18:36:41, 108.07s/it]

Processing tasks:  61%|█████████▏     | 981/1600 [20:31:30<18:17:16, 106.36s/it]

Processing tasks:  61%|█████████▏     | 982/1600 [20:33:19<18:23:42, 107.16s/it]

Processing tasks:  61%|█████████▏     | 983/1600 [20:34:52<17:37:20, 102.82s/it]

Processing tasks:  62%|█████████▏     | 984/1600 [20:36:40<17:50:29, 104.27s/it]

Processing tasks:  62%|█████████▏     | 985/1600 [20:38:29<18:04:17, 105.78s/it]

Processing tasks:  62%|█████████▏     | 986/1600 [20:40:13<17:56:57, 105.24s/it]

Processing tasks:  62%|█████████▎     | 987/1600 [20:42:04<18:13:18, 107.01s/it]

Processing tasks:  62%|█████████▎     | 988/1600 [20:43:54<18:21:20, 107.97s/it]

Processing tasks:  62%|█████████▎     | 989/1600 [20:45:48<18:37:42, 109.76s/it]

Processing tasks:  62%|█████████▎     | 990/1600 [20:47:36<18:29:21, 109.12s/it]

Processing tasks:  62%|█████████▎     | 991/1600 [20:49:22<18:19:24, 108.32s/it]

Processing tasks:  62%|█████████▎     | 992/1600 [20:51:12<18:20:21, 108.59s/it]

Processing tasks:  62%|█████████▎     | 993/1600 [20:53:01<18:22:01, 108.93s/it]

Processing tasks:  62%|█████████▎     | 994/1600 [20:54:40<17:49:20, 105.88s/it]

Processing tasks:  62%|█████████▎     | 995/1600 [20:56:29<17:56:07, 106.72s/it]

Processing tasks:  62%|█████████▎     | 997/1600 [21:00:05<18:00:10, 107.48s/it]

Processing tasks:  62%|█████████▉      | 998/1600 [21:01:20<16:20:41, 97.74s/it]

Processing tasks:  62%|█████████▎     | 999/1600 [21:03:09<16:51:07, 100.94s/it]

Processing tasks:  62%|████████▊     | 1000/1600 [21:04:59<17:18:37, 103.86s/it]

Processing tasks:  63%|████████▊     | 1001/1600 [21:06:47<17:29:49, 105.16s/it]

Processing tasks:  63%|████████▊     | 1002/1600 [21:08:35<17:36:17, 105.98s/it]

Processing tasks:  63%|████████▊     | 1003/1600 [21:10:21<17:32:03, 105.73s/it]

Processing tasks:  63%|████████▊     | 1004/1600 [21:12:08<17:35:40, 106.28s/it]

Processing tasks:  63%|████████▊     | 1006/1600 [21:15:32<17:05:07, 103.55s/it]

Processing tasks:  63%|████████▊     | 1007/1600 [21:17:13<16:55:16, 102.73s/it]

Processing tasks:  63%|█████████▍     | 1008/1600 [21:18:44<16:19:00, 99.22s/it]

Processing tasks:  63%|█████████▍     | 1009/1600 [21:20:11<15:40:20, 95.47s/it]

Processing tasks:  63%|█████████▍     | 1010/1600 [21:21:24<14:31:46, 88.66s/it]

Processing tasks:  63%|█████████▍     | 1011/1600 [21:22:53<14:32:28, 88.88s/it]

Processing tasks:  63%|█████████▍     | 1012/1600 [21:24:14<14:07:54, 86.52s/it]

Processing tasks:  63%|█████████▍     | 1013/1600 [21:25:39<14:02:05, 86.07s/it]

Processing tasks:  63%|█████████▌     | 1014/1600 [21:27:10<14:15:48, 87.63s/it]

Processing tasks:  63%|█████████▌     | 1015/1600 [21:28:35<14:04:46, 86.64s/it]

Processing tasks:  64%|█████████▌     | 1016/1600 [21:30:00<13:59:26, 86.24s/it]

Processing tasks:  64%|█████████▌     | 1017/1600 [21:31:29<14:06:28, 87.12s/it]

Processing tasks:  64%|█████████▌     | 1018/1600 [21:32:55<14:00:09, 86.61s/it]

Processing tasks:  64%|█████████▌     | 1019/1600 [21:34:21<13:56:50, 86.42s/it]

Processing tasks:  64%|█████████▌     | 1020/1600 [21:35:49<14:00:03, 86.90s/it]

Processing tasks:  64%|█████████▌     | 1021/1600 [21:37:21<14:13:32, 88.45s/it]

Processing tasks:  64%|█████████▌     | 1022/1600 [21:38:50<14:14:08, 88.67s/it]

Processing tasks:  64%|█████████▌     | 1023/1600 [21:40:21<14:19:16, 89.35s/it]

Processing tasks:  64%|█████████▌     | 1024/1600 [21:41:38<13:41:36, 85.58s/it]

Processing tasks:  64%|█████████▌     | 1025/1600 [21:43:20<14:28:44, 90.65s/it]

Processing tasks:  64%|█████████▌     | 1026/1600 [21:45:05<15:08:55, 95.01s/it]

Processing tasks:  64%|█████████▋     | 1027/1600 [21:46:51<15:37:49, 98.20s/it]

Processing tasks:  64%|█████████▋     | 1028/1600 [21:48:17<15:01:17, 94.54s/it]

Processing tasks:  64%|█████████▋     | 1029/1600 [21:48:48<11:58:11, 75.47s/it]

Processing tasks:  64%|█████████▋     | 1030/1600 [21:50:14<12:26:23, 78.57s/it]

Processing tasks:  64%|█████████▋     | 1031/1600 [21:51:26<12:08:04, 76.77s/it]

Processing tasks:  64%|█████████▋     | 1032/1600 [21:52:50<12:26:25, 78.85s/it]

Processing tasks:  65%|█████████▋     | 1033/1600 [21:54:17<12:49:19, 81.41s/it]

Processing tasks:  65%|█████████▋     | 1034/1600 [21:55:55<13:34:36, 86.35s/it]

Processing tasks:  65%|█████████▋     | 1035/1600 [21:57:15<13:15:37, 84.49s/it]

Processing tasks:  65%|█████████▋     | 1036/1600 [21:58:40<13:15:20, 84.61s/it]

Processing tasks:  65%|█████████▋     | 1037/1600 [22:00:19<13:53:41, 88.85s/it]

Processing tasks:  65%|█████████▋     | 1038/1600 [22:01:44<13:40:17, 87.58s/it]

Processing tasks:  65%|█████████▋     | 1039/1600 [22:03:08<13:30:32, 86.69s/it]

Processing tasks:  65%|█████████▊     | 1040/1600 [22:04:34<13:27:01, 86.47s/it]

Processing tasks:  65%|█████████▊     | 1041/1600 [22:06:03<13:33:20, 87.30s/it]

Processing tasks:  65%|█████████▊     | 1042/1600 [22:07:37<13:48:50, 89.12s/it]

Processing tasks:  65%|█████████▊     | 1043/1600 [22:08:57<13:22:58, 86.50s/it]

Processing tasks:  65%|█████████▊     | 1044/1600 [22:10:16<12:58:55, 84.06s/it]

Processing tasks:  65%|█████████▊     | 1045/1600 [22:11:41<13:01:04, 84.44s/it]

Processing tasks:  65%|█████████▊     | 1046/1600 [22:13:05<12:58:02, 84.26s/it]

In [ ]:
import requests

def send_push(title, message):
    url = "https://api.pushover.net/1/messages.json"
    payload = {
        "token": "akt9cug1jqigmhnswy2wnh9uvyyoa6",
        "user": "ufk3e4ok2wf77okk9vwhsw3nkiboa4",
        "title": title,
        "message": message
    }
    requests.post(url, data=payload)

# Example usage at end of notebook
send_push(
    "Notebook Completed ✅",
    "Your notebook finished successfully."
)